#######################################################################
#
# This is the low level implementation of the BMC Atrium C-API in Python.
# (C) 2005-2012 by Ergorion
#
# Currently supported Version: V1.1.x of the Atrium API
#
#

import os

from ctypes import CDLL # , cdecl
# from cars import *

# a list of versions (major/minor version) of dll/.h files to check
cmdbversions = ('cmdbapi76', 'cmdbapi75', 'cmdbapi21', 
                'cmdbapi20', 'cmdbapi63', 'arosapi63')
versionDirectories = ('7.5', '7.1', '7.0', '6.3', '6.0', '5.1')

# BMC changed the prefix for the function names in the middle... starting with
# 1.1 patch 002 the prefix changed from AROS to CMDB.
# the following code tries to find out which is which...

foundDLL = False
oldPath = '' # here we store the original system PATH
newPath = '' # here we collect all possible remedy directories

if os.name == 'nt':
    try:
        from _winreg import ConnectRegistry, OpenKey, QueryValueEx,CloseKey,EnumValue,\
                                HKEY_LOCAL_MACHINE, HKEY_CURRENT_USER, KEY_READ
        # prepare different directories that we know of in Registry Current User
        regDirectories = []
        for version in versionDirectories:
            regDirectories.append(('InstallDir', r'Software\Remedy\AR System User\%s' % version))
            regDirectories.append(('InstallDir', r'Software\Remedy\AR System Administrator\%s' % version))
            
        pathList = {HKEY_LOCAL_MACHINE : (('Path', r'Software\Microsoft\Windows\CurrentVersion\App Paths\aruser.exe'),
                    ('Path', r'Software\Microsoft\Windows\CurrentVersion\App Paths\ARADMIN.EXE'),
                    ('', r'SOFTWARE\Classes\TypeLib\{3E92FB98-4B0A-11D1-A94C-00C04FC9BDF2}\1.0\HELPDIR')),
                    HKEY_CURRENT_USER : regDirectories}
        # store the current SYSTEM PATH settings for later reference
        oldPath = os.environ['PATH']
        for key in pathList:
            reg = ConnectRegistry(None, key)
            directories = pathList[key]
            for queryKey, path in directories:
                try:
                    key = OpenKey(reg, path, 0, KEY_READ)
                    arDirectory, id = QueryValueEx(key, queryKey)
                    newPath = '%s;%s' % (newPath, arDirectory)
                    CloseKey(key)
                except WindowsError:
                    pass

        # now also check the registry shared_dlls
        reg = ConnectRegistry(None, HKEY_LOCAL_MACHINE)
        key = OpenKey(reg, 'SOFTWARE\Microsoft\Windows\CurrentVersion\SharedDlls', 0, KEY_READ)
        i = 0
        while True:
            try:
                (entry, value, type) = EnumValue (key, i)
            except WindowsError:
                break
            if entry.rfind('arapi') > -1:
                newPath = '%s;%s' % (newPath, entry[:entry.rfind('\\')])
            i = i+1

    except:
        # if we fail to read the path from the registry, we just continue, hoping
        # that the system path will work...
        pass

    os.environ['PATH'] = '%s;%s' % (oldPath, newPath)
  
    for cmdbversion in cmdbversions:
        try:
            cmdbapi = CDLL('%s.dll' % cmdbversion)
            try:
                # originally I tried to find out which prefix-library we 
                # are using: aros... or cmdb...; turns out, that the later
                # version (with the cmdb prefix) also support the AROS function names
                #error = cmdbapi.CMDBTermination(None, None)
                # we need to get the imported names into car's namespace
                # so that the clients import cars do not need to know about the version!!!
                exec('from _c%s import *' % (cmdbversion))
                foundDLL = True
                break
            except AttributeError:
                raise NotImplementedError, "Could not load Ergorion import %s file" % (version)
            # return (arapi, version)
        except WindowsError: # if this exception is raised, the loading of the API failed; we must
            pass             # capture this exception and continue our loop in order to find the
                             # correct API version...
if not foundDLL:
    print 'FATAL ERROR: Could not load CMDB DLL'
    print 'The current system path is set to the following directories:'
    for directory in oldPath.split(';'):
        print '   ',directory
    if newPath != '':
        print '''I also looked in the Remedy install directories that I found \
in the registry:'''
        for directory in newPath.split(';'):
            print '   ',directory
    else:
        print 'I could not find any Remedy install directory in the registry'
    print
    print 'Please double check your PATH settings!!!'
    import sys
    sys.exit(2)


# define those constants based on the CMDB version we find
if cmdbversion in ['cmdbapi63', 'arosapi63']:
    BMC_namespace='BMC'
    BMC_baseclass='BMC_AssetBase'
    BMC_dataset = 'BMC_ASSET'
elif cmdbversion in ['cmdbapi20', 'cmdbapi21']:  # cmdbapi20 and later
    BMC_namespace='BMC.CORE'
    BMC_baseclass='BMC_BaseElement'
    BMC_dataset = 'BMC_ASSET'    
elif cmdbversion in ['cmdbapi75', 'cmdbapi76']:  # cmdbapi20 and later
    BMC_namespace='BMC.CORE'
    BMC_baseclass='BMC_BaseElement'
    BMC_dataset = 'BMC.ASSET'    


#######################################################################
#
# This is a mapping dictionaries for easier access of
# unions depending on the types... (in order to get rid of
# endless if-elif-else cascades...)

#######################################################################
#
# This is a mapping dictionaries for easier access of
# unions depending on the types... (in order to get rid of
# endless if-elif-else cascades...)

ARValueStruct._mapping_so_ = { AR_DATA_TYPE_KEYWORD: 'u.keyNum',
                  AR_DATA_TYPE_INTEGER: 'u.intVal',
                  AR_DATA_TYPE_REAL: 'u.realVal',
                  AR_DATA_TYPE_CHAR: 'u.charVal',
                  AR_DATA_TYPE_DIARY: 'u.diaryVal',
                  AR_DATA_TYPE_ENUM: 'u.enumVal',
                  AR_DATA_TYPE_TIME: 'u.timeVal',
                  AR_DATA_TYPE_BITMASK: 'u.maskVal',
                  AR_DATA_TYPE_DECIMAL: 'u.decimalVal',
                  AR_DATA_TYPE_ULONG: 'u.ulongVal',
                  AR_DATA_TYPE_DATE: 'u.dateVal',
                  AR_DATA_TYPE_TIME_OF_DAY: 'u.timeOfDayVal' }
    # here comes the mapping for the complex types...
    # problem is, that the structs are defined as pointers in 
    # the C struct -- so we hve to de-reference those first
    # via ctypes: .contents
ARValueStruct._mapping_co_ = {
            AR_DATA_TYPE_BYTES: 'u.byteListVal.contents',
            AR_DATA_TYPE_ATTACH: 'u.attachVal.contents',
            AR_DATA_TYPE_CURRENCY: 'u.currencyVal.contents',
            AR_DATA_TYPE_COORDS: 'u.coordListVal.contents'
        }
#ARActiveLinkActionStruct._mapping_ = { AR_ACTIVE_LINK_ACTION_MACRO: 'u.macro',
#                  AR_ACTIVE_LINK_ACTION_FIELDS: 'u.setFields',
#                  AR_ACTIVE_LINK_ACTION_MESSAGE: 'u.message',
#                  AR_ACTIVE_LINK_ACTION_SET_CHAR: 'u.characteristics',
#                  AR_ACTIVE_LINK_ACTION_DDE: 'u.dde',
#                  AR_ACTIVE_LINK_ACTION_FIELDP: 'u.pushFields',
#                  AR_ACTIVE_LINK_ACTION_SQL: 'u.sqlCommand',
#                  AR_ACTIVE_LINK_ACTION_AUTO: 'u.automation',
#                  AR_ACTIVE_LINK_ACTION_OPENDLG: 'u.openDlg',
#                  AR_ACTIVE_LINK_ACTION_COMMITC: 'u.commitChanges',
#                  AR_ACTIVE_LINK_ACTION_CLOSEWND: 'u.closeWnd',
#                  AR_ACTIVE_LINK_ACTION_CALLGUIDE: 'u.callGuide',
#                  AR_ACTIVE_LINK_ACTION_EXITGUIDE: 'u.exitGuide',
#                  AR_ACTIVE_LINK_ACTION_GOTOGUIDELABEL: 'u.gotoGuide',
#                  AR_ACTIVE_LINK_ACTION_WAIT: 'u.waitAction',
#                  AR_ACTIVE_LINK_ACTION_GOTOACTION: 'u.gotoAction'
#                  }
#######################################################################
#
# This is a mapping of all constants defined for ARS V5.1 to Strings
# for nicer output.
if cmdbversion in ['arosapi63']:
    aros_const = {}
    aros_const['AROS_RESERV_CLASS'] = {
    AROS_RESERV_CLASS_UNIQUE_FORM_IDENTIFIER:"AROS_RESERV_CLASS_UNIQUE_FORM_IDENTIFIER",
        AROS_RESERV_CLASS_NAMESPACE_NAME:"AROS_RESERV_CLASS_NAMESPACE_NAME",
        AROS_RESERV_CLASS_CLASS_NAME:"AROS_RESERV_CLASS_CLASS_NAME",
        AROS_RESERV_CLASS_CLASS_ID:"AROS_RESERV_CLASS_CLASS_ID",
        AROS_RESERV_CLASS_CLASS_TYPE:"AROS_RESERV_CLASS_CLASS_TYPE",
        AROS_RESERV_CLASS_SUPERCLASS:"AROS_RESERV_CLASS_SUPERCLASS",
        AROS_RESERV_CLASS_SINGLETON:"AROS_RESERV_CLASS_SINGLETON",
        AROS_RESERV_CLASS_ABSTRACT:"AROS_RESERV_CLASS_ABSTRACT",
        AROS_RESERV_CLASS_FINAL:"AROS_RESERV_CLASS_FINAL",
        AROS_RESERV_CLASS_CATEGORIZATION_SUBCLASS:"AROS_RESERV_CLASS_CATEGORIZATION_SUBCLASS",
        AROS_RESERV_CLASS_AUTHOR:"AROS_RESERV_CLASS_AUTHOR",
        AROS_RESERV_CLASS_DESCRIPTION:"AROS_RESERV_CLASS_DESCRIPTION",
        AROS_RESERV_CLASS_CUSTOM_CHARACTERISTICS:"AROS_RESERV_CLASS_CUSTOM_CHARACTERISTICS",
        AROS_RESERV_CLASS_CLASS_OBJ_HIDDEN_PERMS:"AROS_RESERV_CLASS_CLASS_OBJ_HIDDEN_PERMS",
        AROS_RESERV_CLASS_CLASS_OBJ_VISIBLE_PERMS:"AROS_RESERV_CLASS_CLASS_OBJ_VISIBLE_PERMS",
        AROS_RESERV_CLASS_META_DATA_STATUS:"AROS_RESERV_CLASS_META_DATA_STATUS",
        AROS_RESERV_CLASS_PENDING_ID:"AROS_RESERV_CLASS_PENDING_ID",
        AROS_RESERV_CLASS_REL_PROPAGATED_ATTRS:"AROS_RESERV_CLASS_REL_PROPAGATED_ATTRS",
        AROS_RESERV_CLASS_REL_CLASS_ID_1:"AROS_RESERV_CLASS_REL_CLASS_ID_1",
        AROS_RESERV_CLASS_REL_CLASS_ID_2:"AROS_RESERV_CLASS_REL_CLASS_ID_2",
        AROS_RESERV_CLASS_REL_ROLE_NAME_1:"AROS_RESERV_CLASS_REL_ROLE_NAME_1",
        AROS_RESERV_CLASS_REL_ROLE_NAME_2:"AROS_RESERV_CLASS_REL_ROLE_NAME_2",
        AROS_RESERV_CLASS_REL_CARDINALITY:"AROS_RESERV_CLASS_REL_CARDINALITY",
        AROS_RESERV_CLASS_REL_RIGHT_SIDE_WEAK_REFERENCE:"AROS_RESERV_CLASS_REL_RIGHT_SIDE_WEAK_REFERENCE",
        AROS_RESERV_CLASS_REL_CASCADE_DELETE:"AROS_RESERV_CLASS_REL_CASCADE_DELETE",
        AROS_RESERV_CLASS_FORM_NAME:"AROS_RESERV_CLASS_FORM_NAME"
        }
    aros_const['AROS_RESERV_ATTR'] = {
    AROS_RESERV_ATTR_UNIQUE_FORM_IDENTIFIER:"AROS_RESERV_ATTR_UNIQUE_FORM_IDENTIFIER",
        AROS_RESERV_ATTR_ATTRIBUTE_NAME:"AROS_RESERV_ATTR_ATTRIBUTE_NAME",
        AROS_RESERV_ATTR_ATTRIBUTE_ID:"AROS_RESERV_ATTR_ATTRIBUTE_ID",
        AROS_RESERV_ATTR_CLASS_ID:"AROS_RESERV_ATTR_CLASS_ID",
        AROS_RESERV_ATTR_FIELD_ID:"AROS_RESERV_ATTR_FIELD_ID",
        AROS_RESERV_ATTR_ENTRY_MODE:"AROS_RESERV_ATTR_ENTRY_MODE",
        AROS_RESERV_ATTR_DATA_TYPE:"AROS_RESERV_ATTR_DATA_TYPE",
        AROS_RESERV_ATTR_ATTRIBUTE_TYPE:"AROS_RESERV_ATTR_ATTRIBUTE_TYPE",
        AROS_RESERV_ATTR_VIEW_PERMS:"AROS_RESERV_ATTR_VIEW_PERMS",
        AROS_RESERV_ATTR_CHANGE_PERMS:"AROS_RESERV_ATTR_CHANGE_PERMS",
        AROS_RESERV_ATTR_CREATE_MODE:"AROS_RESERV_ATTR_CREATE_MODE",
        AROS_RESERV_ATTR_CUSTOM_CHARACTERISTICS:"AROS_RESERV_ATTR_CUSTOM_CHARACTERISTICS",
        AROS_RESERV_ATTR_HIDDEN:"AROS_RESERV_ATTR_HIDDEN",
        AROS_RESERV_ATTR_PRIMARY_KEY:"AROS_RESERV_ATTR_PRIMARY_KEY",
        AROS_RESERV_ATTR_META_DATA_STATUS:"AROS_RESERV_ATTR_META_DATA_STATUS",
        AROS_RESERV_ATTR_PENDING_ID:"AROS_RESERV_ATTR_PENDING_ID",
        AROS_RESERV_ATTR_PROGATED_OWNER:"AROS_RESERV_ATTR_PROGATED_OWNER",
        AROS_RESERV_ATTR_CHAR_MAX_LENGTH:"AROS_RESERV_ATTR_CHAR_MAX_LENGTH",
        AROS_RESERV_ATTR_CHAR_LIST_FORMAT:"AROS_RESERV_ATTR_CHAR_LIST_FORMAT",
        AROS_RESERV_ATTR_CHAR_MENU_STYLE:"AROS_RESERV_ATTR_CHAR_MENU_STYLE",
        AROS_RESERV_ATTR_CHAR_ATTACHED_MENU:"AROS_RESERV_ATTR_CHAR_ATTACHED_MENU",
        AROS_RESERV_ATTR_CHAR_PATTERN:"AROS_RESERV_ATTR_CHAR_PATTERN",
        AROS_RESERV_ATTR_CHAR_QBEMATCH_OPT:"AROS_RESERV_ATTR_CHAR_QBEMATCH_OPT",
        AROS_RESERV_ATTR_INT_MIN:"AROS_RESERV_ATTR_INT_MIN",
        AROS_RESERV_ATTR_INT_MAX:"AROS_RESERV_ATTR_INT_MAX",
        AROS_RESERV_ATTR_REAL_MIN:"AROS_RESERV_ATTR_REAL_MIN",
        AROS_RESERV_ATTR_REAL_MAX:"AROS_RESERV_ATTR_REAL_MAX",
        AROS_RESERV_ATTR_REAL_PRECISION:"AROS_RESERV_ATTR_REAL_PRECISION",
        AROS_RESERV_ATTR_DECIMAL_MIN:"AROS_RESERV_ATTR_DECIMAL_MIN",
        AROS_RESERV_ATTR_DECIMAL_MAX:"AROS_RESERV_ATTR_DECIMAL_MAX",
        AROS_RESERV_ATTR_DECIMAL_PRECISION:"AROS_RESERV_ATTR_DECIMAL_PRECISION",
        AROS_RESERV_ATTR_DATE_MIN:"AROS_RESERV_ATTR_DATE_MIN",
        AROS_RESERV_ATTR_DATE_MAX:"AROS_RESERV_ATTR_DATE_MAX",
        AROS_RESERV_ATTR_ENUM_VALUE:"AROS_RESERV_ATTR_ENUM_VALUE",
        AROS_RESERV_ATTR_CURRENCY_MIN:"AROS_RESERV_ATTR_CURRENCY_MIN",
        AROS_RESERV_ATTR_CURRENCY_MAX:"AROS_RESERV_ATTR_CURRENCY_MAX",
        AROS_RESERV_ATTR_CURRENCY_FUNCTIONAL_TYPES:"AROS_RESERV_ATTR_CURRENCY_FUNCTIONAL_TYPES",
        AROS_RESERV_ATTR_CURRENCY_ALLOWABLE_TYPES:"AROS_RESERV_ATTR_CURRENCY_ALLOWABLE_TYPES",
        AROS_RESERV_ATTR_CURRENCY_PRECISION:"AROS_RESERV_ATTR_CURRENCY_PRECISION",
        AROS_RESERV_ATTR_ATTACH_SIZE:"AROS_RESERV_ATTR_ATTACH_SIZE",
        AROS_RESERV_ATTR_ATTACH_POOL_GUID:"AROS_RESERV_ATTR_ATTACH_POOL_GUID",
        AROS_RESERV_ATTR_CHAR_DEFAULT:"AROS_RESERV_ATTR_CHAR_DEFAULT",
        AROS_RESERV_ATTR_TIME_OF_DAY_DEFAULT:"AROS_RESERV_ATTR_TIME_OF_DAY_DEFAULT",
        AROS_RESERV_ATTR_DATE_DEFAULT:"AROS_RESERV_ATTR_DATE_DEFAULT",
        AROS_RESERV_ATTR_TIME_DEFAULT:"AROS_RESERV_ATTR_TIME_DEFAULT",
        AROS_RESERV_ATTR_DIARY_DEFAULT:"AROS_RESERV_ATTR_DIARY_DEFAULT",
        AROS_RESERV_ATTR_INTEGER_DEFAULT:"AROS_RESERV_ATTR_INTEGER_DEFAULT",
        AROS_RESERV_ATTR_REAL_DEFAULT:"AROS_RESERV_ATTR_REAL_DEFAULT",
        AROS_RESERV_ATTR_DECIMAL_DEFAULT:"AROS_RESERV_ATTR_DECIMAL_DEFAULT",
        AROS_RESERV_ATTR_ENUM_DEFAULT:"AROS_RESERV_ATTR_ENUM_DEFAULT",
        AROS_RESERV_ATTR_CURRENCY_DEFAULT:"AROS_RESERV_ATTR_CURRENCY_DEFAULT"
        }
    aros_const['AROS_RESERV_INDEX'] = {
        AROS_RESERV_INDEX_UNIQUE_FORM_IDENTIFIER:"AROS_RESERV_INDEX_UNIQUE_FORM_IDENTIFIER",
        AROS_RESERV_INDEX_INDEX_NAME:"AROS_RESERV_INDEX_INDEX_NAME",
        AROS_RESERV_INDEX_INDEX_ID:"AROS_RESERV_INDEX_INDEX_ID",
        AROS_RESERV_INDEX_INDEX_UNIQUE:"AROS_RESERV_INDEX_INDEX_UNIQUE",
        AROS_RESERV_INDEX_PENDING_ID:"AROS_RESERV_INDEX_PENDING_ID",
        AROS_RESERV_INDEX_CLASS_ID:"AROS_RESERV_INDEX_CLASS_ID",
        AROS_RESERV_INDEX_PRIMARY_KEY:"AROS_RESERV_INDEX_PRIMARY_KEY",
        AROS_RESERV_INDEX_META_DATA_STATUS:"AROS_RESERV_INDEX_META_DATA_STATUS",
        AROS_RESERV_INDEX_ATTR_UNIQUE_FORM_IDENTIFIER:"AROS_RESERV_INDEX_ATTR_UNIQUE_FORM_IDENTIFIER",
        AROS_RESERV_INDEX_ATTR_GUID:"AROS_RESERV_INDEX_ATTR_GUID",
        AROS_RESERV_INDEX_ATTR_INDEX_ID:"AROS_RESERV_INDEX_ATTR_INDEX_ID",
        AROS_RESERV_INDEX_ATTR_ATTRIBUTE_ID:"AROS_RESERV_INDEX_ATTR_ATTRIBUTE_ID",
        AROS_RESERV_INDEX_ATTR_CLASS_ID:"AROS_RESERV_INDEX_ATTR_CLASS_ID",
        AROS_RESERV_INDEX_ATTR_PENDING_ID:"AROS_RESERV_INDEX_ATTR_PENDING_ID",
        AROS_RESERV_INDEX_ATTR_ORDER:"AROS_RESERV_INDEX_ATTR_ORDER",
        AROS_RESERV_INDEX_ATTR_META_DATA_STATUS:"AROS_RESERV_INDEX_ATTR_META_DATA_STATUS",
        }
    aros_const['AROS_ATTR_DATA_TYPE'] = {
        AROS_ATTR_DATA_TYPE_NULL:"AROS_ATTR_DATA_TYPE_NULL",
        AROS_ATTR_DATA_TYPE_KEYWORD:"AROS_ATTR_DATA_TYPE_KEYWORD",
        AROS_ATTR_DATA_TYPE_INTEGER:"AROS_ATTR_DATA_TYPE_INTEGER",
        AROS_ATTR_DATA_TYPE_REAL:"AROS_ATTR_DATA_TYPE_REAL",
        AROS_ATTR_DATA_TYPE_CHAR:"AROS_ATTR_DATA_TYPE_CHAR",
        AROS_ATTR_DATA_TYPE_DIARY:"AROS_ATTR_DATA_TYPE_DIARY",
        AROS_ATTR_DATA_TYPE_ENUM:"AROS_ATTR_DATA_TYPE_ENUM",
        AROS_ATTR_DATA_TYPE_TIME:"AROS_ATTR_DATA_TYPE_TIME",
        AROS_ATTR_DATA_TYPE_DECIMAL:"AROS_ATTR_DATA_TYPE_DECIMAL",
        AROS_ATTR_DATA_TYPE_ATTACH:"AROS_ATTR_DATA_TYPE_ATTACH",
        AROS_ATTR_DATA_TYPE_CURRENCY:"AROS_ATTR_DATA_TYPE_CURRENCY",
        AROS_ATTR_DATA_TYPE_DATE:"AROS_ATTR_DATA_TYPE_DATE",
        AROS_ATTR_DATA_TYPE_TIME_OF_DAY:"AROS_ATTR_DATA_TYPE_TIME_OF_DAY",
        AROS_ATTR_DATA_TYPE_ATTACH_POOL:"AROS_ATTR_DATA_TYPE_ATTACH_POOL",
        AROS_ATTR_TYPE_NONE:"AROS_ATTR_TYPE_NONE",
        AROS_ATTR_TYPE_CORE_INTERNAL:"AROS_ATTR_TYPE_CORE_INTERNAL",
        AROS_ATTR_TYPE_CORE:"AROS_ATTR_TYPE_CORE",
        AROS_ATTR_TYPE_REGULAR:"AROS_ATTR_TYPE_REGULAR"
    }
    aros_const['AROS_RESERV_NEXTFID'] = {
        AROS_RESERV_NEXTFID_UNIQUE_FORM_IDENTIFIER:"AROS_RESERV_NEXTFID_UNIQUE_FORM_IDENTIFIER",
        AROS_RESERV_NEXTFID_NEXT_FIELD_ID:"AROS_RESERV_NEXTFID_NEXT_FIELD_ID",
    }
    aros_const['AROS_RESERV_SHARED_APP_PROPERTIES'] = {
        AROS_RESERV_SHARED_APP_PROPERTIES_APP_ID:"AROS_RESERV_SHARED_APP_PROPERTIES_APP_ID",
        AROS_RESERV_SHARED_APP_PROPERTIES_NAME:"AROS_RESERV_SHARED_APP_PROPERTIES_NAME",
        AROS_RESERV_SHARED_APP_PROPERTIES_VALUE:"AROS_RESERV_SHARED_APP_PROPERTIES_VALUE",
    }
    aros_const['AROS_RESERV_INSTANCE'] = {
        AROS_RESERV_INSTANCE_VUI:"AROS_RESERV_INSTANCE_VUI",
        AROS_RESERV_INSTANCE_STATIC_CLASS_ID:"AROS_RESERV_INSTANCE_STATIC_CLASS_ID",
        AROS_RESERV_INSTANCE_STATIC_SUPERCLASS_ID:"AROS_RESERV_INSTANCE_STATIC_SUPERCLASS_ID",
        AROS_RESERV_INSTANCE_STATIC_REL_CLASS_ID1:"AROS_RESERV_INSTANCE_STATIC_REL_CLASS_ID1",
        AROS_RESERV_INSTANCE_STATIC_REL_CLASS_ID2:"AROS_RESERV_INSTANCE_STATIC_REL_CLASS_ID2",
        AROS_RESERV_INSTANCE_STATIC_REL_CARDINALITY:"AROS_RESERV_INSTANCE_STATIC_REL_CARDINALITY",
        AROS_RESERV_INSTANCE_STATIC_PUSH_TARGET_1:"AROS_RESERV_INSTANCE_STATIC_PUSH_TARGET_1",
        AROS_RESERV_INSTANCE_STATIC_PUSH_TARGET_2:"AROS_RESERV_INSTANCE_STATIC_PUSH_TARGET_2",
        AROS_RESERV_INSTANCE_STATIC_PUSH_TARGET_3:"AROS_RESERV_INSTANCE_STATIC_PUSH_TARGET_3",
        AROS_RESERV_INSTANCE_STATIC_SINGLETON:"AROS_RESERV_INSTANCE_STATIC_SINGLETON",
        AROS_RESERV_INSTANCE_STATIC_CASCADE_DELETE:"AROS_RESERV_INSTANCE_STATIC_CASCADE_DELETE",
        AROS_RESERV_INSTANCE_STATIC_NAMESPACE_NAME:"AROS_RESERV_INSTANCE_STATIC_NAMESPACE_NAME",
        AROS_RESERV_INSTANCE_STATIC_CLASS_NAME:"AROS_RESERV_INSTANCE_STATIC_CLASS_NAME",
    }
    aros_const['AROS_RESERV_PENDING'] = {
        AROS_RESERV_PENDING_UNIQUE_FORM_IDENTIFIER:"AROS_RESERV_PENDING_UNIQUE_FORM_IDENTIFIER",
        AROS_RESERV_PENDING_CLASS_ID:"AROS_RESERV_PENDING_CLASS_ID",
        AROS_RESERV_PENDING_PENDING_ID:"AROS_RESERV_PENDING_PENDING_ID",
        AROS_RESERV_PENDING_STATUS:"AROS_RESERV_PENDING_STATUS",
        AROS_RESERV_PENDING_STATUS_MESSAGE:"AROS_RESERV_PENDING_STATUS_MESSAGE",
        AROS_RESERV_PENDING_FINISH_DATE:"AROS_RESERV_PENDING_FINISH_DATE",
    }
    aros_const['AROS_RESERV_INSTANCE'] = {
        AROS_RESERV_INSTANCE_GUID:"AROS_RESERV_INSTANCE_GUID",
        AROS_RESERV_INSTANCE_SUBMITTER:"AROS_RESERV_INSTANCE_SUBMITTER",
        AROS_RESERV_INSTANCE_CREATE_DATE:"AROS_RESERV_INSTANCE_CREATE_DATE",
        AROS_RESERV_INSTANCE_LAST_MODIFIED:"AROS_RESERV_INSTANCE_LAST_MODIFIED",
        AROS_RESERV_INSTANCE_MODIFIED_DATE:"AROS_RESERV_INSTANCE_MODIFIED_DATE",
        AROS_RESERV_INSTANCE_CLASS_ID:"AROS_RESERV_INSTANCE_CLASS_ID",
        AROS_RESERV_INSTANCE_DATA_SET_ID:"AROS_RESERV_INSTANCE_DATA_SET_ID",
        AROS_RESERV_INSTANCE_REL_INSTANCE_ID_1:"AROS_RESERV_INSTANCE_REL_INSTANCE_ID_1",
        AROS_RESERV_INSTANCE_REL_INSTANCE_ID_2:"AROS_RESERV_INSTANCE_REL_INSTANCE_ID_2",
        AROS_RESERV_INSTANCE_REL_DATA_SET_ID_1:"AROS_RESERV_INSTANCE_REL_DATA_SET_ID_1",
        AROS_RESERV_INSTANCE_REL_DATA_SET_ID_2:"AROS_RESERV_INSTANCE_REL_DATA_SET_ID_2",
        AROS_RESERV_INSTANCE_REL_CLASS_ID_1:"AROS_RESERV_INSTANCE_REL_CLASS_ID_1",
        AROS_RESERV_INSTANCE_REL_CLASS_ID_2:"AROS_RESERV_INSTANCE_REL_CLASS_ID_2",
        AROS_RESERV_INSTANCE_REL_RECONCIL_ID_1:"AROS_RESERV_INSTANCE_REL_RECONCIL_ID_1",
        AROS_RESERV_INSTANCE_REL_RECONCIL_ID_2:"AROS_RESERV_INSTANCE_REL_RECONCIL_ID_2",
        AROS_RESERV_INSTANCE_REQUEST_ID:"AROS_RESERV_INSTANCE_REQUEST_ID",
        AROS_RESERV_INSTANCE_ASSIGNED_TO:"AROS_RESERV_INSTANCE_ASSIGNED_TO",
        AROS_RESERV_INSTANCE_STATUS:"AROS_RESERV_INSTANCE_STATUS",
        AROS_RESERV_INSTANCE_SHORT_DESCRIPTION:"AROS_RESERV_INSTANCE_SHORT_DESCRIPTION",
        AROS_RESERV_INSTANCE_OP_ORIGINATION_FORM:"AROS_RESERV_INSTANCE_OP_ORIGINATION_FORM",
        AROS_RESERV_INSTANCE_OP_ID_WEAK_REFERENCE:"AROS_RESERV_INSTANCE_OP_ID_WEAK_REFERENCE",
        AROS_RESERV_INSTANCE_DEL_INSTANCE_TRIGGER:"AROS_RESERV_INSTANCE_DEL_INSTANCE_TRIGGER",
        AROS_RESERV_INSTANCE_Z_TMP_DEL_OP_FLAG:"AROS_RESERV_INSTANCE_Z_TMP_DEL_OP_FLAG",
        AROS_RESERV_INSTANCE_Z_TMP_DEL_LEAF_FORM:"AROS_RESERV_INSTANCE_Z_TMP_DEL_LEAF_FORM",
        AROS_RESERV_INSTANCE_Z_TMP_DEL_CASCADE_OP_FLAG:"AROS_RESERV_INSTANCE_Z_TMP_DEL_CASCADE_OP_FLAG",
        AROS_RESERV_INSTANCE_Z_TMP_DEL_CASCADE_RFORM:"AROS_RESERV_INSTANCE_Z_TMP_DEL_CASCADE_RFORM",
        AROS_RESERV_INSTANCE_Z_TMP_DEL_CASCADE_RRID:"AROS_RESERV_INSTANCE_Z_TMP_DEL_CASCADE_RRID",
        AROS_RESERV_INSTANCE_Z_TMP_SDEL_OP_FLAG:"AROS_RESERV_INSTANCE_Z_TMP_SDEL_OP_FLAG",
        AROS_RESERV_INSTANCE_Z_TMP_SDEL_LEAF_FORM:"AROS_RESERV_INSTANCE_Z_TMP_SDEL_LEAF_FORM",
        AROS_RESERV_INSTANCE_Z_TMP_SDEL_CASCADE_OP_FLAG:"AROS_RESERV_INSTANCE_Z_TMP_SDEL_CASCADE_OP_FLAG",
        AROS_RESERV_INSTANCE_Z_TMP_SDEL_CASCADE_RFORM:"AROS_RESERV_INSTANCE_Z_TMP_SDEL_CASCADE_RFORM",
        AROS_RESERV_INSTANCE_Z_TMP_SDEL_CASCADE_RRID:"AROS_RESERV_INSTANCE_Z_TMP_SDEL_CASCADE_RRID",
        AROS_RESERV_INSTANCE_Z_TMP_WEAK_REF_WEAK_FORM:"AROS_RESERV_INSTANCE_Z_TMP_WEAK_REF_WEAK_FORM",
        AROS_RESERV_INSTANCE_Z_TMP_CHAR_1:"AROS_RESERV_INSTANCE_Z_TMP_CHAR_1",
        AROS_RESERV_INSTANCE_Z_TMP_CHAR_2:"AROS_RESERV_INSTANCE_Z_TMP_CHAR_2",
        AROS_RESERV_INSTANCE_Z_TMP_CHAR_3:"AROS_RESERV_INSTANCE_Z_TMP_CHAR_3",
        AROS_RESERV_INSTANCE_Z_TMP_CHAR_4:"AROS_RESERV_INSTANCE_Z_TMP_CHAR_4",
        AROS_RESERV_INSTANCE_Z_TMP_INTEGER_1:"AROS_RESERV_INSTANCE_Z_TMP_INTEGER_1",
        AROS_RESERV_INSTANCE_Z_TMP_INTEGER_2:"AROS_RESERV_INSTANCE_Z_TMP_INTEGER_2",
        AROS_RESERV_INSTANCE_Z_TMP_INTEGER_3:"AROS_RESERV_INSTANCE_Z_TMP_INTEGER_3",
        AROS_RESERV_INSTANCE_Z_TMP_INTEGER_4:"AROS_RESERV_INSTANCE_Z_TMP_INTEGER_4",
        AROS_RESERV_INSTANCE_Z_TMP_INTEGER_8:"AROS_RESERV_INSTANCE_Z_TMP_INTEGER_8",
        AROS_RESERV_INSTANCE_RECONCILIATION_IDENTITY:"AROS_RESERV_INSTANCE_RECONCILIATION_IDENTITY",
        AROS_RESERV_INSTANCE_MARK_AS_DELETED:"AROS_RESERV_INSTANCE_MARK_AS_DELETED",
        AROS_RESERV_INSTANCE_LEAD_INSTANCE_ID:"AROS_RESERV_INSTANCE_LEAD_INSTANCE_ID",
        AROS_RESERV_INSTANCE_LEAD_CLASS_ID:"AROS_RESERV_INSTANCE_LEAD_CLASS_ID",
        AROS_RESERV_INSTANCE_FAILED_AUTOMATIC_IDENTIF:"AROS_RESERV_INSTANCE_FAILED_AUTOMATIC_IDENTIF",
        AROS_RESERV_INSTANCE_DELETED:"AROS_RESERV_INSTANCE_DELETED",
        AROS_RESERV_INSTANCE_Z_TMP_ID_3:"AROS_RESERV_INSTANCE_Z_TMP_ID_3",
        AROS_RESERV_INSTANCE_REL_INSTANCE_ID_NAME:"AROS_RESERV_INSTANCE_REL_INSTANCE_ID_NAME",
        AROS_RESERV_INSTANCE_REL_DATA_SET_ID_NAME:"AROS_RESERV_INSTANCE_REL_DATA_SET_ID_NAME",
        AROS_RESERV_INSTANCE_REL_CLASS_ID_NAME:"AROS_RESERV_INSTANCE_REL_CLASS_ID_NAME",
        AROS_RESERV_INSTANCE_REL_RECONCIL_ID_NAME:"AROS_RESERV_INSTANCE_REL_RECONCIL_ID_NAME",
    }
    aros_const['AROS_ATTR_ID'] = {
        AROS_ATTR_ID_INSTANCE_ID:"AROS_ATTR_ID_INSTANCE_ID",
        AROS_ATTR_ID_SUBMITTER:"AROS_ATTR_ID_SUBMITTER",
        AROS_ATTR_ID_CREATE_DATE:"AROS_ATTR_ID_CREATE_DATE",
        AROS_ATTR_ID_LAST_MODIFIED:"AROS_ATTR_ID_LAST_MODIFIED",
        AROS_ATTR_ID_MODIFIED_DATE:"AROS_ATTR_ID_MODIFIED_DATE",
        AROS_ATTR_ID_CLASS_ID:"AROS_ATTR_ID_CLASS_ID",
        AROS_ATTR_ID_DATA_SET_ID:"AROS_ATTR_ID_DATA_SET_ID",
        AROS_ATTR_ID_REL_INSTANCE_ID_1:"AROS_ATTR_ID_REL_INSTANCE_ID_1",
        AROS_ATTR_ID_REL_INSTANCE_ID_2:"AROS_ATTR_ID_REL_INSTANCE_ID_2",
        AROS_ATTR_ID_REL_DATA_SET_ID_1:"AROS_ATTR_ID_REL_DATA_SET_ID_1",
        AROS_ATTR_ID_REL_DATA_SET_ID_2:"AROS_ATTR_ID_REL_DATA_SET_ID_2",
        AROS_ATTR_ID_REL_CLASS_ID_1:"AROS_ATTR_ID_REL_CLASS_ID_1",
        AROS_ATTR_ID_REL_CLASS_ID_2:"AROS_ATTR_ID_REL_CLASS_ID_2",
        AROS_ATTR_ID_REL_RECONCIL_ID_1:"AROS_ATTR_ID_REL_RECONCIL_ID_1",
        AROS_ATTR_ID_REL_RECONCIL_ID_2:"AROS_ATTR_ID_REL_RECONCIL_ID_2",
        AROS_ATTR_ID_REQUEST_ID:"AROS_ATTR_ID_REQUEST_ID",
        AROS_ATTR_ID_ASSIGNED_TO:"AROS_ATTR_ID_ASSIGNED_TO",
        AROS_ATTR_ID_STATUS:"AROS_ATTR_ID_STATUS",
        AROS_ATTR_ID_SHORT_DESCRIPTION:"AROS_ATTR_ID_SHORT_DESCRIPTION",
        AROS_ATTR_ID_OP_ORIGINATION_FORM:"AROS_ATTR_ID_OP_ORIGINATION_FORM",
        AROS_ATTR_ID_OP_ID_WEAK_REFERENCE:"AROS_ATTR_ID_OP_ID_WEAK_REFERENCE",
        AROS_ATTR_ID_Z_TMP_WEAK_REF_WEAK_FORM:"AROS_ATTR_ID_Z_TMP_WEAK_REF_WEAK_FORM",
        AROS_ATTR_ID_DEL_INSTANCE_TRIGGER:"AROS_ATTR_ID_DEL_INSTANCE_TRIGGER",
        AROS_ATTR_ID_Z_TMP_DEL_OP_FLAG:"AROS_ATTR_ID_Z_TMP_DEL_OP_FLAG",
        AROS_ATTR_ID_Z_TMP_DEL_LEAF_FORM:"AROS_ATTR_ID_Z_TMP_DEL_LEAF_FORM",
        AROS_ATTR_ID_Z_TMP_DEL_CASCADE_OP_FLAG:"AROS_ATTR_ID_Z_TMP_DEL_CASCADE_OP_FLAG",
        AROS_ATTR_ID_Z_TMP_DEL_CASCADE_RFORM:"AROS_ATTR_ID_Z_TMP_DEL_CASCADE_RFORM",
        AROS_ATTR_ID_Z_TMP_DEL_CASCADE_RRID:"AROS_ATTR_ID_Z_TMP_DEL_CASCADE_RRID",
        AROS_ATTR_ID_Z_TMP_SDEL_OP_FLAG:"AROS_ATTR_ID_Z_TMP_SDEL_OP_FLAG",
        AROS_ATTR_ID_Z_TMP_SDEL_LEAF_FORM:"AROS_ATTR_ID_Z_TMP_SDEL_LEAF_FORM",
        AROS_ATTR_ID_Z_TMP_SDEL_CASCADE_OP_FLAG:"AROS_ATTR_ID_Z_TMP_SDEL_CASCADE_OP_FLAG",
        AROS_ATTR_ID_Z_TMP_SDEL_CASCADE_RFORM:"AROS_ATTR_ID_Z_TMP_SDEL_CASCADE_RFORM",
        AROS_ATTR_ID_Z_TMP_SDEL_CASCADE_RRID:"AROS_ATTR_ID_Z_TMP_SDEL_CASCADE_RRID",
        AROS_ATTR_ID_Z_TMP_CHAR_1:"AROS_ATTR_ID_Z_TMP_CHAR_1",
        AROS_ATTR_ID_Z_TMP_CHAR_2:"AROS_ATTR_ID_Z_TMP_CHAR_2",
        AROS_ATTR_ID_Z_TMP_CHAR_3:"AROS_ATTR_ID_Z_TMP_CHAR_3",
        AROS_ATTR_ID_Z_TMP_CHAR_4:"AROS_ATTR_ID_Z_TMP_CHAR_4",
        AROS_ATTR_ID_Z_TMP_INTEGER_1:"AROS_ATTR_ID_Z_TMP_INTEGER_1",
        AROS_ATTR_ID_Z_TMP_INTEGER_2:"AROS_ATTR_ID_Z_TMP_INTEGER_2",
        AROS_ATTR_ID_Z_TMP_INTEGER_3:"AROS_ATTR_ID_Z_TMP_INTEGER_3",
        AROS_ATTR_ID_Z_TMP_INTEGER_4:"AROS_ATTR_ID_Z_TMP_INTEGER_4",
        AROS_ATTR_ID_Z_TMP_INTEGER_8:"AROS_ATTR_ID_Z_TMP_INTEGER_8",
        AROS_ATTR_ID_RECONCILIATION_IDENTITY:"AROS_ATTR_ID_RECONCILIATION_IDENTITY",
        AROS_ATTR_ID_MARK_AS_DELETED:"AROS_ATTR_ID_MARK_AS_DELETED",
        AROS_ATTR_ID_LEAD_INSTANCE_ID:"AROS_ATTR_ID_LEAD_INSTANCE_ID",
        AROS_ATTR_ID_LEAD_CLASS_ID:"AROS_ATTR_ID_LEAD_CLASS_ID",
        AROS_ATTR_ID_FAILED_AUTOMATIC_IDENTIF:"AROS_ATTR_ID_FAILED_AUTOMATIC_IDENTIF",
        AROS_ATTR_ID_DELETED:"AROS_ATTR_ID_DELETED",
        AROS_ATTR_ID_Z_TMP_ID_3:"AROS_ATTR_ID_Z_TMP_ID_3",
    }
    aros_const['AROS_CLASS_CHARAC'] = {
        AROS_CLASS_CHARAC_NONE:"AROS_CLASS_CHARAC_NONE",
        AROS_CLASS_CHARAC_SINGLETON:"AROS_CLASS_CHARAC_SINGLETON",
        AROS_CLASS_CHARAC_ABSTRACT:"AROS_CLASS_CHARAC_ABSTRACT",
        AROS_CLASS_CHARAC_FINAL:"AROS_CLASS_CHARAC_FINAL",
        AROS_CLASS_CHARAC_AUTHOR:"AROS_CLASS_CHARAC_AUTHOR",
        AROS_CLASS_CHARAC_DESCRIPTION:"AROS_CLASS_CHARAC_DESCRIPTION",
        AROS_CLASS_CHARAC_CLASS_HIDDEN_PERMS:"AROS_CLASS_CHARAC_CLASS_HIDDEN_PERMS",
        AROS_CLASS_CHARAC_CLASS_VISIBLE_PERMS:"AROS_CLASS_CHARAC_CLASS_VISIBLE_PERMS",
        AROS_CLASS_CHARAC_CATEGORIZATION_SUBCLASS:"AROS_CLASS_CHARAC_CATEGORIZATION_SUBCLASS",
        AROS_CLASS_CHARAC_FORM_NAME:"AROS_CLASS_CHARAC_FORM_NAME",
    }
    aros_const['AROS_CLASS_CUSTOM_CHARAC'] = {
        AROS_CLASS_CUSTOM_CHARAC_MIN:"AROS_CLASS_CUSTOM_CHARAC_MIN",
        AROS_CLASS_CUSTOM_CHARAC_MAX:"AROS_CLASS_CUSTOM_CHARAC_MAX",
    }
    aros_const['AROS_ATTR_CUSTOM_CHARAC'] = {
        AROS_ATTR_CUSTOM_CHARAC_MIN:"AROS_ATTR_CUSTOM_CHARAC_MIN",
        AROS_ATTR_CUSTOM_CHARAC_MAX:"AROS_ATTR_CUSTOM_CHARAC_MAX",
    }
    aros_const['AROS_ATTR_CHARA'] = {
        AROS_ATTR_CHARAC_NONE:"AROS_ATTR_CHARAC_NONE",
        AROS_ATTR_CHARAC_VIEW_PERMS:"AROS_ATTR_CHARAC_VIEW_PERMS",
        AROS_ATTR_CHARAC_CHANGE_PERMS:"AROS_ATTR_CHARAC_CHANGE_PERMS",
        AROS_ATTR_CHARAC_HIDDEN:"AROS_ATTR_CHARAC_HIDDEN",
        AROS_ATTR_CHARAC_PRIMARY_KEY:"AROS_ATTR_CHARAC_PRIMARY_KEY",
        AROS_ATTR_CHARAC_PROPAGATED_OWNER:"AROS_ATTR_CHARAC_PROPAGATED_OWNER",
        AROS_ATTR_CHARAC_CREATE_MODE:"AROS_ATTR_CHARAC_CREATE_MODE",
    }
    aros_const['AROS_CLASS_TYPE'] = {
        AROS_CLASS_TYPE_NONE:"AROS_CLASS_TYPE_NONE",
        AROS_CLASS_TYPE_REGULAR:"AROS_CLASS_TYPE_REGULAR",
        AROS_CLASS_TYPE_RELATIONSHIP:"AROS_CLASS_TYPE_RELATIONSHIP",
    }
    aros_const['AROS_CLASS_RELATIONSHIP_CARDINALITY'] = {
        AROS_CLASS_RELATIONSHIP_CARDINALITY_NONE:"AROS_CLASS_RELATIONSHIP_CARDINALITY_NONE",
        AROS_CLASS_RELATIONSHIP_CARDINALITY_1_1:"AROS_CLASS_RELATIONSHIP_CARDINALITY_1_1",
        AROS_CLASS_RELATIONSHIP_CARDINALITY_MANY_1:"AROS_CLASS_RELATIONSHIP_CARDINALITY_MANY_1",
        AROS_CLASS_RELATIONSHIP_CARDINALITY_1_MANY:"AROS_CLASS_RELATIONSHIP_CARDINALITY_1_MANY",
        AROS_CLASS_RELATIONSHIP_CARDINALITY_MANY_MANY:"AROS_CLASS_RELATIONSHIP_CARDINALITY_MANY_MANY",
    }
    aros_const['AROS_PERSISTENCE_PROVIDER'] = {
        AROS_PERSISTENCE_PROVIDER_NONE:"AROS_PERSISTENCE_PROVIDER_NONE",
        AROS_PERSISTENCE_PROVIDER_ARS:"AROS_PERSISTENCE_PROVIDER_ARS",
        AROS_PERSISTENCE_PROVIDER_EXTERNAL:"AROS_PERSISTENCE_PROVIDER_EXTERNAL",
    }
    aros_const['AROS_ATTR_ENTRYMODE'] = {
        AROS_ATTR_ENTRYMODE_NONE:"AROS_ATTR_ENTRYMODE_NONE",
        AROS_ATTR_ENTRYMODE_REQUIED:"AROS_ATTR_ENTRYMODE_REQUIED",
        AROS_ATTR_ENTRYMODE_OPTIONAL:"AROS_ATTR_ENTRYMODE_OPTIONAL",
        AROS_ATTR_ENTRYMODE_SYSTEM:"AROS_ATTR_ENTRYMODE_SYSTEM",
        AROS_ATTR_ENTRYMODE_DISPLAY_ONLY:"AROS_ATTR_ENTRYMODE_DISPLAY_ONLY",
    }
    aros_const['AROS_MAX'] = {
        AROS_MAX_NAMESPACE_NAME_SIZE:"AROS_MAX_NAMESPACE_NAME_SIZE",
        AROS_MAX_CLASS_NAME_SIZE:"AROS_MAX_CLASS_NAME_SIZE",
        AROS_MAX_ATTRIBUTE_NAME_SIZE:"AROS_MAX_ATTRIBUTE_NAME_SIZE",
    }
    aros_const['AROS_DELETE_CLASS'] = {
        AROS_DELETE_CLASS_OPTION_NONE:"AROS_DELETE_CLASS_OPTION_NONE",
        AROS_DELETE_CLASS_OPTION_WITH_DATA:"AROS_DELETE_CLASS_OPTION_WITH_DATA",
        AROS_DELETE_CLASS_OPTION_ALL_DEPENDENCIES:"AROS_DELETE_CLASS_OPTION_ALL_DEPENDENCIES",
    }
    aros_const['AR_ATTRIBUTE_DELETE'] = {
        AR_ATTRIBUTE_CLEAN_DELETE:"AR_ATTRIBUTE_CLEAN_DELETE",
        AR_ATTRIBUTE_DATA_DELETE:"AR_ATTRIBUTE_DATA_DELETE",
        AR_ATTRIBUTE_FORCE_DELETE:"AR_ATTRIBUTE_FORCE_DELETE",
    }
    aros_const['AROS_DERIVED_DELOPTION'] = {
        AROS_DERIVED_DELOPTION_NONE:"AROS_DERIVED_DELOPTION_NONE",
        AROS_DERIVED_DELOPTION_FORCE:"AROS_DERIVED_DELOPTION_FORCE",
    }
    aros_const['AROS_PENDING_STATUS'] = {
        AROS_PENDING_STATUS_PENDING:"AROS_PENDING_STATUS_PENDING",
        AROS_PENDING_STATUS_PROCESSING:"AROS_PENDING_STATUS_PROCESSING",
        AROS_PENDING_STATUS_COMPLETE:"AROS_PENDING_STATUS_COMPLETE",
        AROS_PENDING_STATUS_WARNING:"AROS_PENDING_STATUS_WARNING",
        AROS_PENDING_STATUS_ERROR:"AROS_PENDING_STATUS_ERROR",
    }
    aros_const['AROS_META_DATA_STATUS'] = {
        AROS_META_DATA_STATUS_ACTIVE:"AROS_META_DATA_STATUS_ACTIVE",
        AROS_META_DATA_STATUS_DELETE_PENDING:"AROS_META_DATA_STATUS_DELETE_PENDING",
        AROS_META_DATA_STATUS_CHANGE_PENDING:"AROS_META_DATA_STATUS_CHANGE_PENDING",
        AROS_META_DATA_STATUS_DELETE_SYNCING:"AROS_META_DATA_STATUS_DELETE_SYNCING",
        AROS_META_DATA_STATUS_CHANGE_SYNCING:"AROS_META_DATA_STATUS_CHANGE_SYNCING",
    }
    aros_const['AROS_CLASS_ABSTRACT_TYPE'] = {
        AROS_CLASS_ABSTRACT_TYPE_NONE:"AROS_CLASS_ABSTRACT_TYPE_NONE",
        AROS_CLASS_ABSTRACT_TYPE_REGULAR:"AROS_CLASS_ABSTRACT_TYPE_REGULAR",
        AROS_CLASS_ABSTRACT_TYPE_DATA_REPLC:"AROS_CLASS_ABSTRACT_TYPE_DATA_REPLC",
    }
    aros_const['AROS_CLASS_SINGLETON'] = {
        AROS_CLASS_SINGLETON_FALSE:"AROS_CLASS_SINGLETON_FALSE",
        AROS_CLASS_SINGLETON_TRUE:"AROS_CLASS_SINGLETON_TRUE",
    }
    aros_const['AROS_CLASS_FINAL'] = {
        AROS_CLASS_FINAL_FALSE:"AROS_CLASS_FINAL_FALSE",
        AROS_CLASS_FINAL_TRUE:"AROS_CLASS_FINAL_TRUE",
    }
    aros_const['AROS_CLASS_CAT_SUBCLASS'] = {
        AROS_CLASS_CAT_SUBCLASS_FALSE:"AROS_CLASS_CAT_SUBCLASS_FALSE",
        AROS_CLASS_CAT_SUBCLASS_TRUE:"AROS_CLASS_CAT_SUBCLASS_TRUE",
    }
    aros_const['AROS_ATTR_HIDDEN'] = {
        AROS_ATTR_HIDDEN_FALSE:"AROS_ATTR_HIDDEN_FALSE",
        AROS_ATTR_HIDDEN_TRUE:"AROS_ATTR_HIDDEN_TRUE",
    }
    aros_const['AROS_ATTR_PRIMARY_KEY'] = {
        AROS_ATTR_PRIMARY_KEY_FALSE:"AROS_ATTR_PRIMARY_KEY_FALSE",
        AROS_ATTR_PRIMARY_KEY_TRUE:"AROS_ATTR_PRIMARY_KEY_TRUE",
    }
    aros_const['AROS_ATTR_CREATE_MODE'] = {
        AROS_ATTR_CREATE_MODE_NONE:"AROS_ATTR_CREATE_MODE_NONE",
        AROS_ATTR_CREATE_MODE_OPEN:"AROS_ATTR_CREATE_MODE_OPEN",
        AROS_ATTR_CREATE_MODE_PROTECTED:"AROS_ATTR_CREATE_MODE_PROTECTED",
    }
    aros_const['AROS_RELATIONSHIP_DIRECTION'] = {
        AROS_RELATIONSHIP_DIRECTION_OUT:"AROS_RELATIONSHIP_DIRECTION_OUT",
        AROS_RELATIONSHIP_DIRECTION_IN:"AROS_RELATIONSHIP_DIRECTION_IN",
    }
    aros_const['AROS_SORT'] = {
        AROS_SORT_ASCENDING:"AROS_SORT_ASCENDING",
        AROS_SORT_DESCENDING:"AROS_SORT_DESCENDING",
    }
    aros_const['AROS_GET_ATTR'] = {
        AROS_GET_ATTR_NONE:"AROS_GET_ATTR_NONE",
        AROS_GET_ATTR_CUSTOM_LIST:"AROS_GET_ATTR_CUSTOM_LIST",
        AROS_GET_ATTR_NONHIDDEN:"AROS_GET_ATTR_NONHIDDEN",
        AROS_GET_ATTR_ALL:"AROS_GET_ATTR_ALL",
    }
    aros_const['AROS_QUALIFIER_TYPE'] = {
        AROS_QUALIFIER_TYPE_NONE:"AROS_QUALIFIER_TYPE_NONE",
        AROS_QUALIFIER_TYPE_STRING:"AROS_QUALIFIER_TYPE_STRING",
        AROS_QUALIFIER_TYPE_STRUCT:"AROS_QUALIFIER_TYPE_STRUCT",
    }
    aros_const['AROS_WEAK'] = {
        AROS_WEAK_RELATIONSHIP:"AROS_WEAK_RELATIONSHIP",
        AROS_WEAK_OBJECT:"AROS_WEAK_OBJECT",
    }
    aros_const['AROS_ERROR'] = {
        AROS_ERROR_SYSTEM_NOT_INITIALIZED:"AROS_ERROR_SYSTEM_NOT_INITIALIZED",
        AROS_ERROR_SYSTEM_CANNOT_BE_INITIALIZED:"AROS_ERROR_SYSTEM_CANNOT_BE_INITIALIZED",
        AROS_ERROR_NO_SUCH_CLASS:"AROS_ERROR_NO_SUCH_CLASS",
        AROS_ERROR_REQUIRED_PARAM_EMPTY:"AROS_ERROR_REQUIRED_PARAM_EMPTY",
        AROS_ERROR_NO_SUCH_ATTRIBUTE:"AROS_ERROR_NO_SUCH_ATTRIBUTE",
        AROS_ERROR_UNSUPPORTED_ATTRIBUTE_DATA_TYPE:"AROS_ERROR_UNSUPPORTED_ATTRIBUTE_DATA_TYPE",
        AROS_ERROR_INSTANCE_NOT_FOUND:"AROS_ERROR_INSTANCE_NOT_FOUND",
        AROS_ERROR_SYSTEM_ERROR:"AROS_ERROR_SYSTEM_ERROR",
        AROS_ERROR_CLASS_NAME_ID_NOT_UNIQUE:"AROS_ERROR_CLASS_NAME_ID_NOT_UNIQUE",
        AROS_ERROR_CLASS_META_DATA_INVALID:"AROS_ERROR_CLASS_META_DATA_INVALID",
        AROS_ERROR_CLASS_ALREADY_EXISTS:"AROS_ERROR_CLASS_ALREADY_EXISTS",
        AROS_ERROR_CLASS_DOES_NOT_EXIST:"AROS_ERROR_CLASS_DOES_NOT_EXIST",
        AROS_ERROR_INVALID_ABSTRACT_CLASS:"AROS_ERROR_INVALID_ABSTRACT_CLASS",
        AROS_ERROR_ATTRIBUTE_NAME_NOT_UNIQUE:"AROS_ERROR_ATTRIBUTE_NAME_NOT_UNIQUE",
        AROS_ERROR_ATTRIBUTE_ALREADY_EXISTS:"AROS_ERROR_ATTRIBUTE_ALREADY_EXISTS",
        AROS_ERROR_INVALID_ENUM_DEFAULT:"AROS_ERROR_INVALID_ENUM_DEFAULT",
        AROS_ERROR_INVALID_LIST_FORMAT:"AROS_ERROR_INVALID_LIST_FORMAT",
        AROS_ERROR_EXCEED_MAX_LIST_ITEMS:"AROS_ERROR_EXCEED_MAX_LIST_ITEMS",
        AROS_ERROR_ROLE_NAMES_MUST_BE_DIFFERENT:"AROS_ERROR_ROLE_NAMES_MUST_BE_DIFFERENT",
        AROS_ERROR_INVALID_CARDINALITY_VALUE:"AROS_ERROR_INVALID_CARDINALITY_VALUE",
        AROS_ERROR_SUPERCLASS_MUST_BE_REL_CLASS:"AROS_ERROR_SUPERCLASS_MUST_BE_REL_CLASS",
        AROS_ERROR_ROLE_NAME_DOES_NOT_MATCH_SUPERCLASS:"AROS_ERROR_ROLE_NAME_DOES_NOT_MATCH_SUPERCLASS",
        AROS_ERROR_CLASS_ROLE_NOT_SUPERCLASS_DERIVED:"AROS_ERROR_CLASS_ROLE_NOT_SUPERCLASS_DERIVED",
        AROS_ERROR_SUBCLASS_CARDINALITY_LESS_RESTRICTIVE:"AROS_ERROR_SUBCLASS_CARDINALITY_LESS_RESTRICTIVE",
        AROS_ERROR_RELATIONSHIP_PARAM_CANNOT_BE_CHANGED:"AROS_ERROR_RELATIONSHIP_PARAM_CANNOT_BE_CHANGED",
        AROS_ERROR_INVALID_CLASS_TYPE:"AROS_ERROR_INVALID_CLASS_TYPE",
        AROS_ERROR_CLASS_TYPE_CANNOT_BE_CHANGED:"AROS_ERROR_CLASS_TYPE_CANNOT_BE_CHANGED",
        AROS_ERROR_ATTRIBUTE_CANNOT_BE_SET:"AROS_ERROR_ATTRIBUTE_CANNOT_BE_SET",
        AROS_ERROR_ATTRIBUTE_INFO_CORRUPT:"AROS_ERROR_ATTRIBUTE_INFO_CORRUPT",
        AROS_ERROR_INVALID_ABSTRACT_CLASS_INST_OPERATION:"AROS_ERROR_INVALID_ABSTRACT_CLASS_INST_OPERATION",
        AROS_ERROR_INVALID_CATEGORAIZATION_SUBCLASS:"AROS_ERROR_INVALID_CATEGORAIZATION_SUBCLASS",
        AROS_ERROR_INVALID_FINAL_CLASS:"AROS_ERROR_INVALID_FINAL_CLASS",
        AROS_ERROR_INVALID_SINGLETON_CLASS:"AROS_ERROR_INVALID_SINGLETON_CLASS",
        AROS_WARN_INVALID_EXPORT_ITEM_TYPE:"AROS_WARN_INVALID_EXPORT_ITEM_TYPE",
        AROS_ERROR_PERMISSION_LIST_INVALID:"AROS_ERROR_PERMISSION_LIST_INVALID",
        AROS_ERROR_QUERY_GRAPH_HAS_NO_STARTNODE:"AROS_ERROR_QUERY_GRAPH_HAS_NO_STARTNODE",
        AROS_ERROR_QUERY_GRAPH_HAS_AMBIGUOUS_NODE:"AROS_ERROR_QUERY_GRAPH_HAS_AMBIGUOUS_NODE",
        AROS_ERROR_INVALID_SINGLETON_CLASS_INST_OPERATION:"AROS_ERROR_INVALID_SINGLETON_CLASS_INST_OPERATION",
        AROS_ERROR_RELATION_CARDINALITY_CHECK:"AROS_ERROR_RELATION_CARDINALITY_CHECK",
        AROS_ERROR_RELATION_END_PT_DOES_NOT_EXIST:"AROS_ERROR_RELATION_END_PT_DOES_NOT_EXIST",
        AROS_ERROR_CATSUBCLASS_REQD_ATTR_NOT_ALLOWED:"AROS_ERROR_CATSUBCLASS_REQD_ATTR_NOT_ALLOWED",
        AROS_ERROR_SUBCLASS_MUST_BE_RS_WEAK_REFERENCE:"AROS_ERROR_SUBCLASS_MUST_BE_RS_WEAK_REFERENCE",
        AROS_ERROR_INVALID_CARDINALITY_FOR_WEAK_REFERENCE:"AROS_ERROR_INVALID_CARDINALITY_FOR_WEAK_REFERENCE",
        AROS_ERROR_WEAK_INSTANCE_ALREADY_ASSOCIATED:"AROS_ERROR_WEAK_INSTANCE_ALREADY_ASSOCIATED",
        AROS_ERROR_NO_WEAK_RELATION_ABSTRACT_CLASS_ALLOWED:"AROS_ERROR_NO_WEAK_RELATION_ABSTRACT_CLASS_ALLOWED",
        AROS_ERROR_SETTING_LEAD_CLASS_REF_DISALLOWED:"AROS_ERROR_SETTING_LEAD_CLASS_REF_DISALLOWED",
        AROS_ERROR_CANNOT_MODIFY_PRIMARY_KEY_ON_ATTRIBUTE:"AROS_ERROR_CANNOT_MODIFY_PRIMARY_KEY_ON_ATTRIBUTE",
        AROS_ERROR_PRIMARY_KEY_ISNT_UNIQUE:"AROS_ERROR_PRIMARY_KEY_ISNT_UNIQUE",
        AROS_ERROR_MORE_THAN_ONE_PRIMARY_KEY_DISALLOWED:"AROS_ERROR_MORE_THAN_ONE_PRIMARY_KEY_DISALLOWED",
        AROS_ERROR_NO_RHS_CATSUBCLASS_FOR_WEAK_REFERENCE:"AROS_ERROR_NO_RHS_CATSUBCLASS_FOR_WEAK_REFERENCE",
        AROS_ERROR_NO_SUCH_INDEX:"AROS_ERROR_NO_SUCH_INDEX",
        AROS_ERROR_DELETE_CLASS_FAILED_DATA_EXISTS:"AROS_ERROR_DELETE_CLASS_FAILED_DATA_EXISTS",
        AROS_ERROR_DELETE_CLASS_FAILED_DEPENDECIES_EXISTS:"AROS_ERROR_DELETE_CLASS_FAILED_DEPENDECIES_EXISTS",
        AROS_WARN_DELETE_CLASS_FAILED_DEP_REG_CLASS:"AROS_WARN_DELETE_CLASS_FAILED_DEP_REG_CLASS",
        AROS_WARN_DELETE_CLASS_FAILED_DEP_REL_CLASS:"AROS_WARN_DELETE_CLASS_FAILED_DEP_REL_CLASS",
        AROS_WARN_DELETE_CLASS_FAILED_DEP_WEAK_REF_CLASS:"AROS_WARN_DELETE_CLASS_FAILED_DEP_WEAK_REF_CLASS",
        AROS_ERROR_NO_SUCH_SOURCE_ATTRIBUTE_FOR_WEAK_REL:"AROS_ERROR_NO_SUCH_SOURCE_ATTRIBUTE_FOR_WEAK_REL",
        AROS_ERROR_NO_SUCH_TARGET_ATTRIBUTE_FOR_WEAK_REL:"AROS_ERROR_NO_SUCH_TARGET_ATTRIBUTE_FOR_WEAK_REL",
        AROS_ERROR_ATTRIBUTE_DATATYPE_MISMATCH_FOR_WEAK_REL:"AROS_ERROR_ATTRIBUTE_DATATYPE_MISMATCH_FOR_WEAK_REL",
        AROS_ERROR_TARGET_WEAK_ATTR_CANNOT_DERIVED_ATTR:"AROS_ERROR_TARGET_WEAK_ATTR_CANNOT_DERIVED_ATTR",
        AROS_ERROR_CATGORIZATION_SUB_PERM_LIST_INVALID:"AROS_ERROR_CATGORIZATION_SUB_PERM_LIST_INVALID",
        AROS_ERROR_INSTANCE_DELETE_ON_FORM_DISALLOWED:"AROS_ERROR_INSTANCE_DELETE_ON_FORM_DISALLOWED",
        AROS_ERROR_CREATE_GUID_FAILED:"AROS_ERROR_CREATE_GUID_FAILED",
        AROS_WARN_NO_SUCH_ATTACHMENT_POOL:"AROS_WARN_NO_SUCH_ATTACHMENT_POOL",
        AROS_ERROR_SYSTEM_INIT_LICENSE_MODE:"AROS_ERROR_SYSTEM_INIT_LICENSE_MODE",
        AROS_ERROR_IMPORT_ITEM_ITEM:"AROS_ERROR_IMPORT_ITEM_ITEM",
        AROS_ERROR_MISMATCHING_ATTR_DATATYPE:"AROS_ERROR_MISMATCHING_ATTR_DATATYPE",
        AROS_ERROR_ATTRIBUTE_VALUE_OUT_OF_LIMITS:"AROS_ERROR_ATTRIBUTE_VALUE_OUT_OF_LIMITS",
        AROS_ERROR_INVALID_INDEX_LIST:"AROS_ERROR_INVALID_INDEX_LIST",
        AROS_ERROR_SETTING_FORM_NAME_CHARAC_DISALLOWED:"AROS_ERROR_SETTING_FORM_NAME_CHARAC_DISALLOWED",
        AROS_ERROR_INVALID_DATATYPE_FOR_CLASS_CHARAC:"AROS_ERROR_INVALID_DATATYPE_FOR_CLASS_CHARAC",
        AROS_ERROR_NAMESPACE_NAME_TOO_LONG:"AROS_ERROR_NAMESPACE_NAME_TOO_LONG",
        AROS_ERROR_CLASS_NAME_TOO_LONG:"AROS_ERROR_CLASS_NAME_TOO_LONG",
        AROS_ERROR_SUBCLASS_SUPERCLASS_NAMESPACE_MISMATCH:"AROS_ERROR_SUBCLASS_SUPERCLASS_NAMESPACE_MISMATCH",
        AROS_ERROR_REQUIRED_ATTRIBUTE_VALUE_MISSING:"AROS_ERROR_REQUIRED_ATTRIBUTE_VALUE_MISSING",
        AROS_ERROR_MODIFY_NAMESPACE_NAME_IS_DISALLOWED:"AROS_ERROR_MODIFY_NAMESPACE_NAME_IS_DISALLOWED",
        AROS_ERROR_CHARACTER_DISALLOWED_IN_NAME:"AROS_ERROR_CHARACTER_DISALLOWED_IN_NAME",
        AROS_ERROR_ATTRIBUTE_NAME_TOO_LONG:"AROS_ERROR_ATTRIBUTE_NAME_TOO_LONG",
        AROS_ERROR_INVALID_ATTRIBUTE_ENTRY_MODE:"AROS_ERROR_INVALID_ATTRIBUTE_ENTRY_MODE",
        AROS_ERROR_ATTR_FIELD_ID_NOT_UNIQUE:"AROS_ERROR_ATTR_FIELD_ID_NOT_UNIQUE",
        AROS_ERROR_INVALID_DATATYPE_FOR_ATTR_CHARAC:"AROS_ERROR_INVALID_DATATYPE_FOR_ATTR_CHARAC",
        AROS_ERROR_SETTING_PRIMARY_KEY_CHARAC_DISALLOWED:"AROS_ERROR_SETTING_PRIMARY_KEY_CHARAC_DISALLOWED",
        AROS_ERROR_SETTING_PROP_OWNER_CHARAC_DISALLOWED:"AROS_ERROR_SETTING_PROP_OWNER_CHARAC_DISALLOWED",
        AROS_ERROR_REL_END_POINT_CLASS_NAMESPACE_MISMATCH:"AROS_ERROR_REL_END_POINT_CLASS_NAMESPACE_MISMATCH",
        AROS_ERROR_ENUM_NAME_INVALID:"AROS_ERROR_ENUM_NAME_INVALID",
        AROS_ERROR_ATTRIBUTE_ID_NOT_UNIQUE:"AROS_ERROR_ATTRIBUTE_ID_NOT_UNIQUE",
        AROS_ERROR_INVALID_ATTR_LIMIT_DATA_TYPE:"AROS_ERROR_INVALID_ATTR_LIMIT_DATA_TYPE",
        AROS_ERROR_NO_ACCESS_TO_CLASS:"AROS_ERROR_NO_ACCESS_TO_CLASS",
        AROS_ERROR_NO_ACCESS_TO_ATTRIBUTE:"AROS_ERROR_NO_ACCESS_TO_ATTRIBUTE",
        AROS_ERROR_OS_SYSTEM_USER_DOES_NOT_EXIST:"AROS_ERROR_OS_SYSTEM_USER_DOES_NOT_EXIST",
        AROS_ERROR_DATASET_ID_RECON_ID_NOT_UNIQUE:"AROS_ERROR_DATASET_ID_RECON_ID_NOT_UNIQUE",
        AROS_ERROR_INVALID_CLASS_ID:"AROS_ERROR_INVALID_CLASS_ID",
        AROS_ERROR_QUERY_GRAPH_INVALID_DIRECTION:"AROS_ERROR_QUERY_GRAPH_INVALID_DIRECTION",
        AROS_ERROR_CURRENT_API_IS_DEPRECATED:"AROS_ERROR_CURRENT_API_IS_DEPRECATED",
        AROS_WARN_IMPORT_INST_SKIPPED:"AROS_WARN_IMPORT_INST_SKIPPED",
        AROS_INFO_IMPORT_INST_SUMMARY:"AROS_INFO_IMPORT_INST_SUMMARY",
        AROS_ERROR_INVALID_DELETE_OPTION:"AROS_ERROR_INVALID_DELETE_OPTION",
        AROS_ERROR_INVALID_META_DATA_STATUS:"AROS_ERROR_INVALID_META_DATA_STATUS",
        AROS_ERROR_INVALID_REL_ENDPOINT_CLASS_ID:"AROS_ERROR_INVALID_REL_ENDPOINT_CLASS_ID",
        AROS_ERROR_ACCESS_TLS_BLOCK_FAILED:"AROS_ERROR_ACCESS_TLS_BLOCK_FAILED",
        AROS_ERROR_UNRECOGNIZED_VERSION_PATCH_STRING:"AROS_ERROR_UNRECOGNIZED_VERSION_PATCH_STRING",
        AROS_ERROR_INVALID_CASCADE_DELETE_VALUE:"AROS_ERROR_INVALID_CASCADE_DELETE_VALUE",
    }
    aros_const['AROS_ITEM_TYPE'] = {
        AROS_ITEM_TYPE_META_DATA:"AROS_ITEM_TYPE_META_DATA",
        AROS_ITEM_TYPE_INSTANCE_DATA:"AROS_ITEM_TYPE_INSTANCE_DATA",
    }
    aros_const['AROS_EXPORT_OPTION'] = {
        AROS_EXPORT_OPTION_NONE:"AROS_EXPORT_OPTION_NONE",
        AROS_EXPORT_OPTION_CLASS_ONLY:"AROS_EXPORT_OPTION_CLASS_ONLY",
        AROS_EXPORT_OPTION_SUPER_CLASSES:"AROS_EXPORT_OPTION_SUPER_CLASSES",
        AROS_EXPORT_OPTION_SUB_CLASSES:"AROS_EXPORT_OPTION_SUB_CLASSES",
    }
    aros_const['AROS_LOC'] = {
        AROS_LOC_NULL:"AROS_LOC_NULL",
        AROS_LOC_FILENAME:"AROS_LOC_FILENAME",
        AROS_LOC_BUFFER:"AROS_LOC_BUFFER",
    }
    aros_const['AROS_VER'] = {
        AROS_VER_MAJOR:"AROS_VER_MAJOR",
        AROS_VER_MINOR:"AROS_VER_MINOR",
        AROS_VER_MAINTENANCE:"AROS_VER_MAINTENANCE",
        AROS_VER_PATCH:"AROS_VER_PATCH"
        }
    aros_const['rest'] = {
        AR_GUID_BUF_LEN:"AR_GUID_BUF_LEN",
        AROS_EXPORT_FORMAT_XML:"AROS_EXPORT_FORMAT_XML",
        AROS_STRING_SEPARATOR:"AROS_STRING_SEPARATOR",
        AROS_SYSTEM_INIT_LICENSE_MODE:"AROS_SYSTEM_INIT_LICENSE_MODE",
        AROS_START_WITH_FIRST_INSTANCE:"AROS_START_WITH_FIRST_INSTANCE",
        AROS_NO_MAX_LIST_RETRIEVE:"AROS_NO_MAX_LIST_RETRIEVE",
        AROS_RESERV_TYPE_MGMT_META_DATA_RECORD_STATUS:"AROS_RESERV_TYPE_MGMT_META_DATA_RECORD_STATUS",
    }

if cmdbversion in ['cmdbapi20', 'cmdbapi63', 'arosapi63']:
    
    cmdb_const = {}
    cmdb_const['CMDB_ATTR_DATA_TYPE'] = {
        CMDB_ATTR_DATA_TYPE_NULL:"CMDB_ATTR_DATA_TYPE_NULL",
        CMDB_ATTR_DATA_TYPE_KEYWORD:"CMDB_ATTR_DATA_TYPE_KEYWORD",
        CMDB_ATTR_DATA_TYPE_INTEGER:"CMDB_ATTR_DATA_TYPE_INTEGER",
        CMDB_ATTR_DATA_TYPE_REAL:"CMDB_ATTR_DATA_TYPE_REAL",
        CMDB_ATTR_DATA_TYPE_CHAR:"CMDB_ATTR_DATA_TYPE_CHAR",
        CMDB_ATTR_DATA_TYPE_DIARY:"CMDB_ATTR_DATA_TYPE_DIARY",
        CMDB_ATTR_DATA_TYPE_ENUM:"CMDB_ATTR_DATA_TYPE_ENUM",
        CMDB_ATTR_DATA_TYPE_TIME:"CMDB_ATTR_DATA_TYPE_TIME",
        CMDB_ATTR_DATA_TYPE_DECIMAL:"CMDB_ATTR_DATA_TYPE_DECIMAL",
        CMDB_ATTR_DATA_TYPE_ATTACH:"CMDB_ATTR_DATA_TYPE_ATTACH",
        CMDB_ATTR_DATA_TYPE_CURRENCY:"CMDB_ATTR_DATA_TYPE_CURRENCY",
        CMDB_ATTR_DATA_TYPE_DATE:"CMDB_ATTR_DATA_TYPE_DATE",
        CMDB_ATTR_DATA_TYPE_TIME_OF_DAY:"CMDB_ATTR_DATA_TYPE_TIME_OF_DAY",
        CMDB_ATTR_DATA_TYPE_ATTACH_POOL:"CMDB_ATTR_DATA_TYPE_ATTACH_POOL"
        }
    cmdb_const['CMDB_ATTR_TYPE'] = {
        CMDB_ATTR_TYPE_NONE:"CMDB_ATTR_TYPE_NONE",
        CMDB_ATTR_TYPE_CORE_INTERNAL:"CMDB_ATTR_TYPE_CORE_INTERNAL",
        CMDB_ATTR_TYPE_CORE:"CMDB_ATTR_TYPE_CORE",
        CMDB_ATTR_TYPE_REGULAR:"CMDB_ATTR_TYPE_REGULAR"
        }
    cmdb_const['CMDB_RESERV_CLASS'] = {
        CMDB_RESERV_CLASS_UNIQUE_FORM_IDENTIFIER:"CMDB_RESERV_CLASS_UNIQUE_FORM_IDENTIFIER",
        CMDB_RESERV_CLASS_NAMESPACE_NAME:"CMDB_RESERV_CLASS_NAMESPACE_NAME",
        CMDB_RESERV_CLASS_CLASS_NAME:"CMDB_RESERV_CLASS_CLASS_NAME",
        CMDB_RESERV_CLASS_CLASS_ID:"CMDB_RESERV_CLASS_CLASS_ID",
        CMDB_RESERV_CLASS_CLASS_TYPE:"CMDB_RESERV_CLASS_CLASS_TYPE",
        CMDB_RESERV_CLASS_SUPERCLASS:"CMDB_RESERV_CLASS_SUPERCLASS",
        CMDB_RESERV_CLASS_SINGLETON:"CMDB_RESERV_CLASS_SINGLETON",
        CMDB_RESERV_CLASS_ABSTRACT:"CMDB_RESERV_CLASS_ABSTRACT",
        CMDB_RESERV_CLASS_FINAL:"CMDB_RESERV_CLASS_FINAL",
        CMDB_RESERV_CLASS_CATEGORIZATION_SUBCLASS:"CMDB_RESERV_CLASS_CATEGORIZATION_SUBCLASS",
        CMDB_RESERV_CLASS_AUTHOR:"CMDB_RESERV_CLASS_AUTHOR",
        CMDB_RESERV_CLASS_DESCRIPTION:"CMDB_RESERV_CLASS_DESCRIPTION",
        CMDB_RESERV_CLASS_CUSTOM_CHARACTERISTICS:"CMDB_RESERV_CLASS_CUSTOM_CHARACTERISTICS",
        CMDB_RESERV_CLASS_CLASS_OBJ_HIDDEN_PERMS:"CMDB_RESERV_CLASS_CLASS_OBJ_HIDDEN_PERMS",
        CMDB_RESERV_CLASS_CLASS_OBJ_VISIBLE_PERMS:"CMDB_RESERV_CLASS_CLASS_OBJ_VISIBLE_PERMS",
        CMDB_RESERV_CLASS_META_DATA_STATUS:"CMDB_RESERV_CLASS_META_DATA_STATUS",
        CMDB_RESERV_CLASS_PENDING_ID:"CMDB_RESERV_CLASS_PENDING_ID",
        CMDB_RESERV_CLASS_REL_PROPAGATED_ATTRS:"CMDB_RESERV_CLASS_REL_PROPAGATED_ATTRS",
        CMDB_RESERV_CLASS_REL_CLASS_ID_1:"CMDB_RESERV_CLASS_REL_CLASS_ID_1",
        CMDB_RESERV_CLASS_REL_CLASS_ID_2:"CMDB_RESERV_CLASS_REL_CLASS_ID_2",
        CMDB_RESERV_CLASS_REL_ROLE_NAME_1:"CMDB_RESERV_CLASS_REL_ROLE_NAME_1",
        CMDB_RESERV_CLASS_REL_ROLE_NAME_2:"CMDB_RESERV_CLASS_REL_ROLE_NAME_2",
        CMDB_RESERV_CLASS_REL_CARDINALITY:"CMDB_RESERV_CLASS_REL_CARDINALITY",
        CMDB_RESERV_CLASS_REL_RIGHT_SIDE_WEAK_REFERENCE:"CMDB_RESERV_CLASS_REL_RIGHT_SIDE_WEAK_REFERENCE",
        CMDB_RESERV_CLASS_REL_CASCADE_DELETE:"CMDB_RESERV_CLASS_REL_CASCADE_DELETE",
        CMDB_RESERV_CLASS_FORM_NAME:"CMDB_RESERV_CLASS_FORM_NAME"
        }
    cmdb_const['CMDB_RESERV_ATTR'] = {
        CMDB_RESERV_ATTR_UNIQUE_FORM_IDENTIFIER:"CMDB_RESERV_ATTR_UNIQUE_FORM_IDENTIFIER",
        CMDB_RESERV_ATTR_ATTRIBUTE_NAME:"CMDB_RESERV_ATTR_ATTRIBUTE_NAME",
        CMDB_RESERV_ATTR_ATTRIBUTE_ID:"CMDB_RESERV_ATTR_ATTRIBUTE_ID",
        CMDB_RESERV_ATTR_CLASS_ID:"CMDB_RESERV_ATTR_CLASS_ID",
        CMDB_RESERV_ATTR_FIELD_ID:"CMDB_RESERV_ATTR_FIELD_ID",
        CMDB_RESERV_ATTR_ENTRY_MODE:"CMDB_RESERV_ATTR_ENTRY_MODE",
        CMDB_RESERV_ATTR_DATA_TYPE:"CMDB_RESERV_ATTR_DATA_TYPE",
        CMDB_RESERV_ATTR_ATTRIBUTE_TYPE:"CMDB_RESERV_ATTR_ATTRIBUTE_TYPE",
        CMDB_RESERV_ATTR_VIEW_PERMS:"CMDB_RESERV_ATTR_VIEW_PERMS",
        CMDB_RESERV_ATTR_CHANGE_PERMS:"CMDB_RESERV_ATTR_CHANGE_PERMS",
        CMDB_RESERV_ATTR_CREATE_MODE:"CMDB_RESERV_ATTR_CREATE_MODE",
        CMDB_RESERV_ATTR_CUSTOM_CHARACTERISTICS:"CMDB_RESERV_ATTR_CUSTOM_CHARACTERISTICS",
        CMDB_RESERV_ATTR_HIDDEN:"CMDB_RESERV_ATTR_HIDDEN",
        CMDB_RESERV_ATTR_PRIMARY_KEY:"CMDB_RESERV_ATTR_PRIMARY_KEY",
        CMDB_RESERV_ATTR_META_DATA_STATUS:"CMDB_RESERV_ATTR_META_DATA_STATUS",
        CMDB_RESERV_ATTR_PENDING_ID:"CMDB_RESERV_ATTR_PENDING_ID",
        CMDB_RESERV_ATTR_PROGATED_OWNER:"CMDB_RESERV_ATTR_PROGATED_OWNER",
        CMDB_RESERV_ATTR_CHAR_MAX_LENGTH:"CMDB_RESERV_ATTR_CHAR_MAX_LENGTH",
        CMDB_RESERV_ATTR_CHAR_LIST_FORMAT:"CMDB_RESERV_ATTR_CHAR_LIST_FORMAT",
        CMDB_RESERV_ATTR_CHAR_MENU_STYLE:"CMDB_RESERV_ATTR_CHAR_MENU_STYLE",
        CMDB_RESERV_ATTR_CHAR_ATTACHED_MENU:"CMDB_RESERV_ATTR_CHAR_ATTACHED_MENU",
        CMDB_RESERV_ATTR_CHAR_PATTERN:"CMDB_RESERV_ATTR_CHAR_PATTERN",
        CMDB_RESERV_ATTR_CHAR_QBEMATCH_OPT:"CMDB_RESERV_ATTR_CHAR_QBEMATCH_OPT",
        CMDB_RESERV_ATTR_INT_MIN:"CMDB_RESERV_ATTR_INT_MIN",
        CMDB_RESERV_ATTR_INT_MAX:"CMDB_RESERV_ATTR_INT_MAX",
        CMDB_RESERV_ATTR_REAL_MIN:"CMDB_RESERV_ATTR_REAL_MIN",
        CMDB_RESERV_ATTR_REAL_MAX:"CMDB_RESERV_ATTR_REAL_MAX",
        CMDB_RESERV_ATTR_REAL_PRECISION:"CMDB_RESERV_ATTR_REAL_PRECISION",
        CMDB_RESERV_ATTR_DECIMAL_MIN:"CMDB_RESERV_ATTR_DECIMAL_MIN",
        CMDB_RESERV_ATTR_DECIMAL_MAX:"CMDB_RESERV_ATTR_DECIMAL_MAX",
        CMDB_RESERV_ATTR_DECIMAL_PRECISION:"CMDB_RESERV_ATTR_DECIMAL_PRECISION",
        CMDB_RESERV_ATTR_DATE_MIN:"CMDB_RESERV_ATTR_DATE_MIN",
        CMDB_RESERV_ATTR_DATE_MAX:"CMDB_RESERV_ATTR_DATE_MAX",
        CMDB_RESERV_ATTR_ENUM_VALUE:"CMDB_RESERV_ATTR_ENUM_VALUE",
        CMDB_RESERV_ATTR_CURRENCY_MIN:"CMDB_RESERV_ATTR_CURRENCY_MIN",
        CMDB_RESERV_ATTR_CURRENCY_MAX:"CMDB_RESERV_ATTR_CURRENCY_MAX",
        CMDB_RESERV_ATTR_CURRENCY_FUNCTIONAL_TYPES:"CMDB_RESERV_ATTR_CURRENCY_FUNCTIONAL_TYPES",
        CMDB_RESERV_ATTR_CURRENCY_ALLOWABLE_TYPES:"CMDB_RESERV_ATTR_CURRENCY_ALLOWABLE_TYPES",
        CMDB_RESERV_ATTR_CURRENCY_PRECISION:"CMDB_RESERV_ATTR_CURRENCY_PRECISION",
        CMDB_RESERV_ATTR_ATTACH_SIZE:"CMDB_RESERV_ATTR_ATTACH_SIZE",
        CMDB_RESERV_ATTR_ATTACH_POOL_GUID:"CMDB_RESERV_ATTR_ATTACH_POOL_GUID",
        CMDB_RESERV_ATTR_CHAR_DEFAULT:"CMDB_RESERV_ATTR_CHAR_DEFAULT",
        CMDB_RESERV_ATTR_TIME_OF_DAY_DEFAULT:"CMDB_RESERV_ATTR_TIME_OF_DAY_DEFAULT",
        CMDB_RESERV_ATTR_DATE_DEFAULT:"CMDB_RESERV_ATTR_DATE_DEFAULT",
        CMDB_RESERV_ATTR_TIME_DEFAULT:"CMDB_RESERV_ATTR_TIME_DEFAULT",
        CMDB_RESERV_ATTR_DIARY_DEFAULT:"CMDB_RESERV_ATTR_DIARY_DEFAULT",
        CMDB_RESERV_ATTR_INTEGER_DEFAULT:"CMDB_RESERV_ATTR_INTEGER_DEFAULT",
        CMDB_RESERV_ATTR_REAL_DEFAULT:"CMDB_RESERV_ATTR_REAL_DEFAULT",
        CMDB_RESERV_ATTR_DECIMAL_DEFAULT:"CMDB_RESERV_ATTR_DECIMAL_DEFAULT",
        CMDB_RESERV_ATTR_ENUM_DEFAULT:"CMDB_RESERV_ATTR_ENUM_DEFAULT",
        CMDB_RESERV_ATTR_CURRENCY_DEFAULT:"CMDB_RESERV_ATTR_CURRENCY_DEFAULT"
    }
    cmdb_const['CMDB_RESERV_NEXTFID'] = {
        CMDB_RESERV_NEXTFID_UNIQUE_FORM_IDENTIFIER:"CMDB_RESERV_NEXTFID_UNIQUE_FORM_IDENTIFIER",
        CMDB_RESERV_NEXTFID_NEXT_FIELD_ID:"CMDB_RESERV_NEXTFID_NEXT_FIELD_ID",
    }
    cmdb_const['CMDB_RESERV_SHARED_APP_PROPERTIES'] = {
        CMDB_RESERV_SHARED_APP_PROPERTIES_APP_ID:"CMDB_RESERV_SHARED_APP_PROPERTIES_APP_ID",
        CMDB_RESERV_SHARED_APP_PROPERTIES_NAME:"CMDB_RESERV_SHARED_APP_PROPERTIES_NAME",
        CMDB_RESERV_SHARED_APP_PROPERTIES_VALUE:"CMDB_RESERV_SHARED_APP_PROPERTIES_VALUE",
    }
    cmdb_const['CMDB_RESERV_INDEX'] = {
        CMDB_RESERV_INDEX_UNIQUE_FORM_IDENTIFIER:"CMDB_RESERV_INDEX_UNIQUE_FORM_IDENTIFIER",
        CMDB_RESERV_INDEX_INDEX_NAME:"CMDB_RESERV_INDEX_INDEX_NAME",
        CMDB_RESERV_INDEX_INDEX_ID:"CMDB_RESERV_INDEX_INDEX_ID",
        CMDB_RESERV_INDEX_INDEX_UNIQUE:"CMDB_RESERV_INDEX_INDEX_UNIQUE",
        CMDB_RESERV_INDEX_PENDING_ID:"CMDB_RESERV_INDEX_PENDING_ID",
        CMDB_RESERV_INDEX_CLASS_ID:"CMDB_RESERV_INDEX_CLASS_ID",
        CMDB_RESERV_INDEX_PRIMARY_KEY:"CMDB_RESERV_INDEX_PRIMARY_KEY",
        CMDB_RESERV_INDEX_META_DATA_STATUS:"CMDB_RESERV_INDEX_META_DATA_STATUS",
    }
    cmdb_const['CMDB_RESERV_INDEX_ATTR'] = {
        CMDB_RESERV_INDEX_ATTR_UNIQUE_FORM_IDENTIFIER:"CMDB_RESERV_INDEX_ATTR_UNIQUE_FORM_IDENTIFIER",
        CMDB_RESERV_INDEX_ATTR_GUID:"CMDB_RESERV_INDEX_ATTR_GUID",
        CMDB_RESERV_INDEX_ATTR_INDEX_ID:"CMDB_RESERV_INDEX_ATTR_INDEX_ID",
        CMDB_RESERV_INDEX_ATTR_ATTRIBUTE_ID:"CMDB_RESERV_INDEX_ATTR_ATTRIBUTE_ID",
        CMDB_RESERV_INDEX_ATTR_CLASS_ID:"CMDB_RESERV_INDEX_ATTR_CLASS_ID",
        CMDB_RESERV_INDEX_ATTR_PENDING_ID:"CMDB_RESERV_INDEX_ATTR_PENDING_ID",
        CMDB_RESERV_INDEX_ATTR_ORDER:"CMDB_RESERV_INDEX_ATTR_ORDER",
        CMDB_RESERV_INDEX_ATTR_META_DATA_STATUS:"CMDB_RESERV_INDEX_ATTR_META_DATA_STATUS",
    }
    cmdb_const['CMDB_RESERV_INSTANCE'] = {
        CMDB_RESERV_INSTANCE_VUI:"CMDB_RESERV_INSTANCE_VUI",
        CMDB_RESERV_INSTANCE_STATIC_CLASS_ID:"CMDB_RESERV_INSTANCE_STATIC_CLASS_ID",
        CMDB_RESERV_INSTANCE_STATIC_SUPERCLASS_ID:"CMDB_RESERV_INSTANCE_STATIC_SUPERCLASS_ID",
        CMDB_RESERV_INSTANCE_STATIC_REL_CLASS_ID1:"CMDB_RESERV_INSTANCE_STATIC_REL_CLASS_ID1",
        CMDB_RESERV_INSTANCE_STATIC_REL_CLASS_ID2:"CMDB_RESERV_INSTANCE_STATIC_REL_CLASS_ID2",
        CMDB_RESERV_INSTANCE_STATIC_REL_CARDINALITY:"CMDB_RESERV_INSTANCE_STATIC_REL_CARDINALITY",
        CMDB_RESERV_INSTANCE_STATIC_PUSH_TARGET_1:"CMDB_RESERV_INSTANCE_STATIC_PUSH_TARGET_1",
        CMDB_RESERV_INSTANCE_STATIC_PUSH_TARGET_2:"CMDB_RESERV_INSTANCE_STATIC_PUSH_TARGET_2",
        CMDB_RESERV_INSTANCE_STATIC_PUSH_TARGET_3:"CMDB_RESERV_INSTANCE_STATIC_PUSH_TARGET_3",
        CMDB_RESERV_INSTANCE_STATIC_SINGLETON:"CMDB_RESERV_INSTANCE_STATIC_SINGLETON",
        CMDB_RESERV_INSTANCE_STATIC_CASCADE_DELETE:"CMDB_RESERV_INSTANCE_STATIC_CASCADE_DELETE",
        CMDB_RESERV_INSTANCE_STATIC_NAMESPACE_NAME:"CMDB_RESERV_INSTANCE_STATIC_NAMESPACE_NAME",
        CMDB_RESERV_INSTANCE_STATIC_CLASS_NAME:"CMDB_RESERV_INSTANCE_STATIC_CLASS_NAME",
    }
    cmdb_const['CMDB_RESERV_PENDING'] = {
        CMDB_RESERV_PENDING_UNIQUE_FORM_IDENTIFIER:"CMDB_RESERV_PENDING_UNIQUE_FORM_IDENTIFIER",
        CMDB_RESERV_PENDING_CLASS_ID:"CMDB_RESERV_PENDING_CLASS_ID",
        CMDB_RESERV_PENDING_PENDING_ID:"CMDB_RESERV_PENDING_PENDING_ID",
        CMDB_RESERV_PENDING_STATUS:"CMDB_RESERV_PENDING_STATUS",
        CMDB_RESERV_PENDING_STATUS_MESSAGE:"CMDB_RESERV_PENDING_STATUS_MESSAGE",
        CMDB_RESERV_PENDING_FINISH_DATE:"CMDB_RESERV_PENDING_FINISH_DATE",
    }
    cmdb_const['CMDB_RESERV_INSTANCE'] = {
        CMDB_RESERV_INSTANCE_GUID:"CMDB_RESERV_INSTANCE_GUID",
        CMDB_RESERV_INSTANCE_SUBMITTER:"CMDB_RESERV_INSTANCE_SUBMITTER",
        CMDB_RESERV_INSTANCE_CREATE_DATE:"CMDB_RESERV_INSTANCE_CREATE_DATE",
        CMDB_RESERV_INSTANCE_LAST_MODIFIED:"CMDB_RESERV_INSTANCE_LAST_MODIFIED",
        CMDB_RESERV_INSTANCE_MODIFIED_DATE:"CMDB_RESERV_INSTANCE_MODIFIED_DATE",
        CMDB_RESERV_INSTANCE_CLASS_ID:"CMDB_RESERV_INSTANCE_CLASS_ID",
        CMDB_RESERV_INSTANCE_DATA_SET_ID:"CMDB_RESERV_INSTANCE_DATA_SET_ID",
        CMDB_RESERV_INSTANCE_REL_INSTANCE_ID_1:"CMDB_RESERV_INSTANCE_REL_INSTANCE_ID_1",
        CMDB_RESERV_INSTANCE_REL_INSTANCE_ID_2:"CMDB_RESERV_INSTANCE_REL_INSTANCE_ID_2",
        CMDB_RESERV_INSTANCE_REL_DATA_SET_ID_1:"CMDB_RESERV_INSTANCE_REL_DATA_SET_ID_1",
        CMDB_RESERV_INSTANCE_REL_DATA_SET_ID_2:"CMDB_RESERV_INSTANCE_REL_DATA_SET_ID_2",
        CMDB_RESERV_INSTANCE_REL_CLASS_ID_1:"CMDB_RESERV_INSTANCE_REL_CLASS_ID_1",
        CMDB_RESERV_INSTANCE_REL_CLASS_ID_2:"CMDB_RESERV_INSTANCE_REL_CLASS_ID_2",
        CMDB_RESERV_INSTANCE_REL_RECONCIL_ID_1:"CMDB_RESERV_INSTANCE_REL_RECONCIL_ID_1",
        CMDB_RESERV_INSTANCE_REL_RECONCIL_ID_2:"CMDB_RESERV_INSTANCE_REL_RECONCIL_ID_2",
        CMDB_RESERV_INSTANCE_REQUEST_ID:"CMDB_RESERV_INSTANCE_REQUEST_ID",
        CMDB_RESERV_INSTANCE_ASSIGNED_TO:"CMDB_RESERV_INSTANCE_ASSIGNED_TO",
        CMDB_RESERV_INSTANCE_STATUS:"CMDB_RESERV_INSTANCE_STATUS",
        CMDB_RESERV_INSTANCE_SHORT_DESCRIPTION:"CMDB_RESERV_INSTANCE_SHORT_DESCRIPTION",
        CMDB_RESERV_INSTANCE_OP_ORIGINATION_FORM:"CMDB_RESERV_INSTANCE_OP_ORIGINATION_FORM",
        CMDB_RESERV_INSTANCE_OP_ID_WEAK_REFERENCE:"CMDB_RESERV_INSTANCE_OP_ID_WEAK_REFERENCE",
        CMDB_RESERV_INSTANCE_DEL_INSTANCE_TRIGGER:"CMDB_RESERV_INSTANCE_DEL_INSTANCE_TRIGGER",
        CMDB_RESERV_INSTANCE_Z_TMP_DEL_OP_FLAG:"CMDB_RESERV_INSTANCE_Z_TMP_DEL_OP_FLAG",
        CMDB_RESERV_INSTANCE_Z_TMP_DEL_LEAF_FORM:"CMDB_RESERV_INSTANCE_Z_TMP_DEL_LEAF_FORM",
        CMDB_RESERV_INSTANCE_Z_TMP_DEL_CASCADE_OP_FLAG:"CMDB_RESERV_INSTANCE_Z_TMP_DEL_CASCADE_OP_FLAG",
        CMDB_RESERV_INSTANCE_Z_TMP_DEL_CASCADE_RFORM:"CMDB_RESERV_INSTANCE_Z_TMP_DEL_CASCADE_RFORM",
        CMDB_RESERV_INSTANCE_Z_TMP_DEL_CASCADE_RRID:"CMDB_RESERV_INSTANCE_Z_TMP_DEL_CASCADE_RRID",
        CMDB_RESERV_INSTANCE_Z_TMP_SDEL_OP_FLAG:"CMDB_RESERV_INSTANCE_Z_TMP_SDEL_OP_FLAG",
        CMDB_RESERV_INSTANCE_Z_TMP_SDEL_LEAF_FORM:"CMDB_RESERV_INSTANCE_Z_TMP_SDEL_LEAF_FORM",
        CMDB_RESERV_INSTANCE_Z_TMP_SDEL_CASCADE_OP_FLAG:"CMDB_RESERV_INSTANCE_Z_TMP_SDEL_CASCADE_OP_FLAG",
        CMDB_RESERV_INSTANCE_Z_TMP_SDEL_CASCADE_RFORM:"CMDB_RESERV_INSTANCE_Z_TMP_SDEL_CASCADE_RFORM",
        CMDB_RESERV_INSTANCE_Z_TMP_SDEL_CASCADE_RRID:"CMDB_RESERV_INSTANCE_Z_TMP_SDEL_CASCADE_RRID",
        CMDB_RESERV_INSTANCE_Z_TMP_WEAK_REF_WEAK_FORM:"CMDB_RESERV_INSTANCE_Z_TMP_WEAK_REF_WEAK_FORM",
        CMDB_RESERV_INSTANCE_Z_TMP_CHAR_1:"CMDB_RESERV_INSTANCE_Z_TMP_CHAR_1",
        CMDB_RESERV_INSTANCE_Z_TMP_CHAR_2:"CMDB_RESERV_INSTANCE_Z_TMP_CHAR_2",
        CMDB_RESERV_INSTANCE_Z_TMP_CHAR_3:"CMDB_RESERV_INSTANCE_Z_TMP_CHAR_3",
        CMDB_RESERV_INSTANCE_Z_TMP_CHAR_4:"CMDB_RESERV_INSTANCE_Z_TMP_CHAR_4",
        CMDB_RESERV_INSTANCE_Z_TMP_INTEGER_1:"CMDB_RESERV_INSTANCE_Z_TMP_INTEGER_1",
        CMDB_RESERV_INSTANCE_Z_TMP_INTEGER_2:"CMDB_RESERV_INSTANCE_Z_TMP_INTEGER_2",
        CMDB_RESERV_INSTANCE_Z_TMP_INTEGER_3:"CMDB_RESERV_INSTANCE_Z_TMP_INTEGER_3",
        CMDB_RESERV_INSTANCE_Z_TMP_INTEGER_4:"CMDB_RESERV_INSTANCE_Z_TMP_INTEGER_4",
        CMDB_RESERV_INSTANCE_Z_TMP_INTEGER_8:"CMDB_RESERV_INSTANCE_Z_TMP_INTEGER_8",
        CMDB_RESERV_INSTANCE_RECONCILIATION_IDENTITY:"CMDB_RESERV_INSTANCE_RECONCILIATION_IDENTITY",
        CMDB_RESERV_INSTANCE_MARK_AS_DELETED:"CMDB_RESERV_INSTANCE_MARK_AS_DELETED",
        CMDB_RESERV_INSTANCE_LEAD_INSTANCE_ID:"CMDB_RESERV_INSTANCE_LEAD_INSTANCE_ID",
        CMDB_RESERV_INSTANCE_LEAD_CLASS_ID:"CMDB_RESERV_INSTANCE_LEAD_CLASS_ID",
        CMDB_RESERV_INSTANCE_FAILED_AUTOMATIC_IDENTIF:"CMDB_RESERV_INSTANCE_FAILED_AUTOMATIC_IDENTIF",
        CMDB_RESERV_INSTANCE_DELETED:"CMDB_RESERV_INSTANCE_DELETED",
        CMDB_RESERV_INSTANCE_Z_TMP_ID_3:"CMDB_RESERV_INSTANCE_Z_TMP_ID_3",
        CMDB_RESERV_INSTANCE_REL_INSTANCE_ID_NAME:"CMDB_RESERV_INSTANCE_REL_INSTANCE_ID_NAME",
        CMDB_RESERV_INSTANCE_REL_DATA_SET_ID_NAME:"CMDB_RESERV_INSTANCE_REL_DATA_SET_ID_NAME",
        CMDB_RESERV_INSTANCE_REL_CLASS_ID_NAME:"CMDB_RESERV_INSTANCE_REL_CLASS_ID_NAME",
        CMDB_RESERV_INSTANCE_REL_RECONCIL_ID_NAME:"CMDB_RESERV_INSTANCE_REL_RECONCIL_ID_NAME",
    }
    cmdb_const['CMDB_ATTR_ID'] = {
        CMDB_ATTR_ID_INSTANCE_ID:"CMDB_ATTR_ID_INSTANCE_ID",
        CMDB_ATTR_ID_SUBMITTER:"CMDB_ATTR_ID_SUBMITTER",
        CMDB_ATTR_ID_CREATE_DATE:"CMDB_ATTR_ID_CREATE_DATE",
        CMDB_ATTR_ID_LAST_MODIFIED:"CMDB_ATTR_ID_LAST_MODIFIED",
        CMDB_ATTR_ID_MODIFIED_DATE:"CMDB_ATTR_ID_MODIFIED_DATE",
        CMDB_ATTR_ID_CLASS_ID:"CMDB_ATTR_ID_CLASS_ID",
        CMDB_ATTR_ID_DATA_SET_ID:"CMDB_ATTR_ID_DATA_SET_ID",
        CMDB_ATTR_ID_REL_INSTANCE_ID_1:"CMDB_ATTR_ID_REL_INSTANCE_ID_1",
        CMDB_ATTR_ID_REL_INSTANCE_ID_2:"CMDB_ATTR_ID_REL_INSTANCE_ID_2",
        CMDB_ATTR_ID_REL_DATA_SET_ID_1:"CMDB_ATTR_ID_REL_DATA_SET_ID_1",
        CMDB_ATTR_ID_REL_DATA_SET_ID_2:"CMDB_ATTR_ID_REL_DATA_SET_ID_2",
        CMDB_ATTR_ID_REL_CLASS_ID_1:"CMDB_ATTR_ID_REL_CLASS_ID_1",
        CMDB_ATTR_ID_REL_CLASS_ID_2:"CMDB_ATTR_ID_REL_CLASS_ID_2",
        CMDB_ATTR_ID_REL_RECONCIL_ID_1:"CMDB_ATTR_ID_REL_RECONCIL_ID_1",
        CMDB_ATTR_ID_REL_RECONCIL_ID_2:"CMDB_ATTR_ID_REL_RECONCIL_ID_2",
        CMDB_ATTR_ID_REQUEST_ID:"CMDB_ATTR_ID_REQUEST_ID",
        CMDB_ATTR_ID_ASSIGNED_TO:"CMDB_ATTR_ID_ASSIGNED_TO",
        CMDB_ATTR_ID_STATUS:"CMDB_ATTR_ID_STATUS",
        CMDB_ATTR_ID_SHORT_DESCRIPTION:"CMDB_ATTR_ID_SHORT_DESCRIPTION",
        CMDB_ATTR_ID_OP_ORIGINATION_FORM:"CMDB_ATTR_ID_OP_ORIGINATION_FORM",
        CMDB_ATTR_ID_OP_ID_WEAK_REFERENCE:"CMDB_ATTR_ID_OP_ID_WEAK_REFERENCE",
        CMDB_ATTR_ID_Z_TMP_WEAK_REF_WEAK_FORM:"CMDB_ATTR_ID_Z_TMP_WEAK_REF_WEAK_FORM",
        CMDB_ATTR_ID_DEL_INSTANCE_TRIGGER:"CMDB_ATTR_ID_DEL_INSTANCE_TRIGGER",
        CMDB_ATTR_ID_Z_TMP_DEL_OP_FLAG:"CMDB_ATTR_ID_Z_TMP_DEL_OP_FLAG",
        CMDB_ATTR_ID_Z_TMP_DEL_LEAF_FORM:"CMDB_ATTR_ID_Z_TMP_DEL_LEAF_FORM",
        CMDB_ATTR_ID_Z_TMP_DEL_CASCADE_OP_FLAG:"CMDB_ATTR_ID_Z_TMP_DEL_CASCADE_OP_FLAG",
        CMDB_ATTR_ID_Z_TMP_DEL_CASCADE_RFORM:"CMDB_ATTR_ID_Z_TMP_DEL_CASCADE_RFORM",
        CMDB_ATTR_ID_Z_TMP_DEL_CASCADE_RRID:"CMDB_ATTR_ID_Z_TMP_DEL_CASCADE_RRID",
        CMDB_ATTR_ID_Z_TMP_SDEL_OP_FLAG:"CMDB_ATTR_ID_Z_TMP_SDEL_OP_FLAG",
        CMDB_ATTR_ID_Z_TMP_SDEL_LEAF_FORM:"CMDB_ATTR_ID_Z_TMP_SDEL_LEAF_FORM",
        CMDB_ATTR_ID_Z_TMP_SDEL_CASCADE_OP_FLAG:"CMDB_ATTR_ID_Z_TMP_SDEL_CASCADE_OP_FLAG",
        CMDB_ATTR_ID_Z_TMP_SDEL_CASCADE_RFORM:"CMDB_ATTR_ID_Z_TMP_SDEL_CASCADE_RFORM",
        CMDB_ATTR_ID_Z_TMP_SDEL_CASCADE_RRID:"CMDB_ATTR_ID_Z_TMP_SDEL_CASCADE_RRID",
        CMDB_ATTR_ID_Z_TMP_CHAR_1:"CMDB_ATTR_ID_Z_TMP_CHAR_1",
        CMDB_ATTR_ID_Z_TMP_CHAR_2:"CMDB_ATTR_ID_Z_TMP_CHAR_2",
        CMDB_ATTR_ID_Z_TMP_CHAR_3:"CMDB_ATTR_ID_Z_TMP_CHAR_3",
        CMDB_ATTR_ID_Z_TMP_CHAR_4:"CMDB_ATTR_ID_Z_TMP_CHAR_4",
        CMDB_ATTR_ID_Z_TMP_INTEGER_1:"CMDB_ATTR_ID_Z_TMP_INTEGER_1",
        CMDB_ATTR_ID_Z_TMP_INTEGER_2:"CMDB_ATTR_ID_Z_TMP_INTEGER_2",
        CMDB_ATTR_ID_Z_TMP_INTEGER_3:"CMDB_ATTR_ID_Z_TMP_INTEGER_3",
        CMDB_ATTR_ID_Z_TMP_INTEGER_4:"CMDB_ATTR_ID_Z_TMP_INTEGER_4",
        CMDB_ATTR_ID_Z_TMP_INTEGER_8:"CMDB_ATTR_ID_Z_TMP_INTEGER_8",
        CMDB_ATTR_ID_RECONCILIATION_IDENTITY:"CMDB_ATTR_ID_RECONCILIATION_IDENTITY",
        CMDB_ATTR_ID_MARK_AS_DELETED:"CMDB_ATTR_ID_MARK_AS_DELETED",
        CMDB_ATTR_ID_LEAD_INSTANCE_ID:"CMDB_ATTR_ID_LEAD_INSTANCE_ID",
        CMDB_ATTR_ID_LEAD_CLASS_ID:"CMDB_ATTR_ID_LEAD_CLASS_ID",
        CMDB_ATTR_ID_FAILED_AUTOMATIC_IDENTIF:"CMDB_ATTR_ID_FAILED_AUTOMATIC_IDENTIF",
        CMDB_ATTR_ID_DELETED:"CMDB_ATTR_ID_DELETED",
        CMDB_ATTR_ID_Z_TMP_ID_3:"CMDB_ATTR_ID_Z_TMP_ID_3",
    }
    cmdb_const['CMDB_CLASS_CHARAC'] = {
        CMDB_CLASS_CHARAC_NONE:"CMDB_CLASS_CHARAC_NONE",
        CMDB_CLASS_CHARAC_SINGLETON:"CMDB_CLASS_CHARAC_SINGLETON",
        CMDB_CLASS_CHARAC_ABSTRACT:"CMDB_CLASS_CHARAC_ABSTRACT",
        CMDB_CLASS_CHARAC_FINAL:"CMDB_CLASS_CHARAC_FINAL",
        CMDB_CLASS_CHARAC_AUTHOR:"CMDB_CLASS_CHARAC_AUTHOR",
        CMDB_CLASS_CHARAC_DESCRIPTION:"CMDB_CLASS_CHARAC_DESCRIPTION",
        CMDB_CLASS_CHARAC_CLASS_HIDDEN_PERMS:"CMDB_CLASS_CHARAC_CLASS_HIDDEN_PERMS",
        CMDB_CLASS_CHARAC_CLASS_VISIBLE_PERMS:"CMDB_CLASS_CHARAC_CLASS_VISIBLE_PERMS",
        CMDB_CLASS_CHARAC_CATEGORIZATION_SUBCLASS:"CMDB_CLASS_CHARAC_CATEGORIZATION_SUBCLASS",
        CMDB_CLASS_CHARAC_FORM_NAME:"CMDB_CLASS_CHARAC_FORM_NAME",
    }
    cmdb_const['CMDB_CLASS_CUSTOM_CHARAC'] = {
        CMDB_CLASS_CUSTOM_CHARAC_MIN:"CMDB_CLASS_CUSTOM_CHARAC_MIN",
        CMDB_CLASS_CUSTOM_CHARAC_MAX:"CMDB_CLASS_CUSTOM_CHARAC_MAX",
    }
    cmdb_const['CMDB_ATTR_CUSTOM_CHARAC'] = {
        CMDB_ATTR_CUSTOM_CHARAC_MIN:"CMDB_ATTR_CUSTOM_CHARAC_MIN",
        CMDB_ATTR_CUSTOM_CHARAC_MAX:"CMDB_ATTR_CUSTOM_CHARAC_MAX",
    }
    cmdb_const['CMDB_ATTR_CHARAC'] = {
        CMDB_ATTR_CHARAC_NONE:"CMDB_ATTR_CHARAC_NONE",
        CMDB_ATTR_CHARAC_VIEW_PERMS:"CMDB_ATTR_CHARAC_VIEW_PERMS",
        CMDB_ATTR_CHARAC_CHANGE_PERMS:"CMDB_ATTR_CHARAC_CHANGE_PERMS",
        CMDB_ATTR_CHARAC_HIDDEN:"CMDB_ATTR_CHARAC_HIDDEN",
        CMDB_ATTR_CHARAC_PRIMARY_KEY:"CMDB_ATTR_CHARAC_PRIMARY_KEY",
        CMDB_ATTR_CHARAC_PROPAGATED_OWNER:"CMDB_ATTR_CHARAC_PROPAGATED_OWNER",
        CMDB_ATTR_CHARAC_CREATE_MODE:"CMDB_ATTR_CHARAC_CREATE_MODE",
    }
    cmdb_const['CMDB_CLASS_TYPE'] = {
        CMDB_CLASS_TYPE_NONE:"CMDB_CLASS_TYPE_NONE",
        CMDB_CLASS_TYPE_REGULAR:"CMDB_CLASS_TYPE_REGULAR",
        CMDB_CLASS_TYPE_RELATIONSHIP:"CMDB_CLASS_TYPE_RELATIONSHIP",
    }
    cmdb_const['CMDB_CLASS_RELATIONSHIP_CARDINALITY'] = {
        CMDB_CLASS_RELATIONSHIP_CARDINALITY_NONE:"CMDB_CLASS_RELATIONSHIP_CARDINALITY_NONE",
        CMDB_CLASS_RELATIONSHIP_CARDINALITY_1_1:"CMDB_CLASS_RELATIONSHIP_CARDINALITY_1_1",
        CMDB_CLASS_RELATIONSHIP_CARDINALITY_MANY_1:"CMDB_CLASS_RELATIONSHIP_CARDINALITY_MANY_1",
        CMDB_CLASS_RELATIONSHIP_CARDINALITY_1_MANY:"CMDB_CLASS_RELATIONSHIP_CARDINALITY_1_MANY",
        CMDB_CLASS_RELATIONSHIP_CARDINALITY_MANY_MANY:"CMDB_CLASS_RELATIONSHIP_CARDINALITY_MANY_MANY",
    }
    cmdb_const['CMDB_PERSISTENCE_PROVIDER'] = {
        CMDB_PERSISTENCE_PROVIDER_NONE:"CMDB_PERSISTENCE_PROVIDER_NONE",
        CMDB_PERSISTENCE_PROVIDER_ARS:"CMDB_PERSISTENCE_PROVIDER_ARS",
        CMDB_PERSISTENCE_PROVIDER_EXTERNAL:"CMDB_PERSISTENCE_PROVIDER_EXTERNAL",
    }
    cmdb_const['CMDB_ATTR_ENTRYMODE'] = {
        CMDB_ATTR_ENTRYMODE_NONE:"CMDB_ATTR_ENTRYMODE_NONE",
        CMDB_ATTR_ENTRYMODE_REQUIED:"CMDB_ATTR_ENTRYMODE_REQUIED",
        CMDB_ATTR_ENTRYMODE_OPTIONAL:"CMDB_ATTR_ENTRYMODE_OPTIONAL",
        CMDB_ATTR_ENTRYMODE_SYSTEM:"CMDB_ATTR_ENTRYMODE_SYSTEM",
        CMDB_ATTR_ENTRYMODE_DISPLAY_ONLY:"CMDB_ATTR_ENTRYMODE_DISPLAY_ONLY",
    }
    cmdb_const['CMDB_MAX'] = {
        CMDB_MAX_NAMESPACE_NAME_SIZE:"CMDB_MAX_NAMESPACE_NAME_SIZE",
        CMDB_MAX_CLASS_NAME_SIZE:"CMDB_MAX_CLASS_NAME_SIZE",
        CMDB_MAX_ATTRIBUTE_NAME_SIZE:"CMDB_MAX_ATTRIBUTE_NAME_SIZE",
    }
    cmdb_const['CMDB_DELETE_CLASS'] = {
        CMDB_DELETE_CLASS_OPTION_NONE:"CMDB_DELETE_CLASS_OPTION_NONE",
        CMDB_DELETE_CLASS_OPTION_WITH_DATA:"CMDB_DELETE_CLASS_OPTION_WITH_DATA",
        CMDB_DELETE_CLASS_OPTION_ALL_DEPENDENCIES:"CMDB_DELETE_CLASS_OPTION_ALL_DEPENDENCIES",
    }
    cmdb_const['AR_ATTRIBUTE_DELETE'] = {
        AR_ATTRIBUTE_CLEAN_DELETE:"AR_ATTRIBUTE_CLEAN_DELETE",
        AR_ATTRIBUTE_DATA_DELETE:"AR_ATTRIBUTE_DATA_DELETE",
        AR_ATTRIBUTE_FORCE_DELETE:"AR_ATTRIBUTE_FORCE_DELETE",
    }
    cmdb_const['CMDB_DERIVED_DELOPTION'] = {
        CMDB_DERIVED_DELOPTION_NONE:"CMDB_DERIVED_DELOPTION_NONE",
        CMDB_DERIVED_DELOPTION_FORCE:"CMDB_DERIVED_DELOPTION_FORCE",
    }
    cmdb_const['CMDB_PENDING_STATUS'] = {
        CMDB_PENDING_STATUS_PENDING:"CMDB_PENDING_STATUS_PENDING",
        CMDB_PENDING_STATUS_PROCESSING:"CMDB_PENDING_STATUS_PROCESSING",
        CMDB_PENDING_STATUS_COMPLETE:"CMDB_PENDING_STATUS_COMPLETE",
        CMDB_PENDING_STATUS_WARNING:"CMDB_PENDING_STATUS_WARNING",
        CMDB_PENDING_STATUS_ERROR:"CMDB_PENDING_STATUS_ERROR",
    }
    cmdb_const['CMDB_META_DATA_STATUS'] = {
        CMDB_META_DATA_STATUS_ACTIVE:"CMDB_META_DATA_STATUS_ACTIVE",
        CMDB_META_DATA_STATUS_DELETE_PENDING:"CMDB_META_DATA_STATUS_DELETE_PENDING",
        CMDB_META_DATA_STATUS_CHANGE_PENDING:"CMDB_META_DATA_STATUS_CHANGE_PENDING",
        CMDB_META_DATA_STATUS_DELETE_SYNCING:"CMDB_META_DATA_STATUS_DELETE_SYNCING",
        CMDB_META_DATA_STATUS_CHANGE_SYNCING:"CMDB_META_DATA_STATUS_CHANGE_SYNCING",
    }
    cmdb_const['CMDB_CLASS_ABSTRACT_TYPE'] = {
        CMDB_CLASS_ABSTRACT_TYPE_NONE:"CMDB_CLASS_ABSTRACT_TYPE_NONE",
        CMDB_CLASS_ABSTRACT_TYPE_REGULAR:"CMDB_CLASS_ABSTRACT_TYPE_REGULAR",
        CMDB_CLASS_ABSTRACT_TYPE_DATA_REPLC:"CMDB_CLASS_ABSTRACT_TYPE_DATA_REPLC",
    }
    cmdb_const['CMDB_CLASS_SINGLETON'] = {
        CMDB_CLASS_SINGLETON_FALSE:"CMDB_CLASS_SINGLETON_FALSE",
        CMDB_CLASS_SINGLETON_TRUE:"CMDB_CLASS_SINGLETON_TRUE",
    }
    cmdb_const['CMDB_CLASS_FINAL'] = {
        CMDB_CLASS_FINAL_FALSE:"CMDB_CLASS_FINAL_FALSE",
        CMDB_CLASS_FINAL_TRUE:"CMDB_CLASS_FINAL_TRUE",
    }
    cmdb_const['CMDB_CLASS_CAT_SUBCLASS'] = {
        CMDB_CLASS_CAT_SUBCLASS_FALSE:"CMDB_CLASS_CAT_SUBCLASS_FALSE",
        CMDB_CLASS_CAT_SUBCLASS_TRUE:"CMDB_CLASS_CAT_SUBCLASS_TRUE",
    }
    cmdb_const['CMDB_ATTR_HIDDEN'] = {
        CMDB_ATTR_HIDDEN_FALSE:"CMDB_ATTR_HIDDEN_FALSE",
        CMDB_ATTR_HIDDEN_TRUE:"CMDB_ATTR_HIDDEN_TRUE",
    }
    cmdb_const['CMDB_ATTR_PRIMARY_KEY'] = {
        CMDB_ATTR_PRIMARY_KEY_FALSE:"CMDB_ATTR_PRIMARY_KEY_FALSE",
        CMDB_ATTR_PRIMARY_KEY_TRUE:"CMDB_ATTR_PRIMARY_KEY_TRUE",
    }
    cmdb_const['CMDB_ATTR_CREATE_MODE'] = {
        CMDB_ATTR_CREATE_MODE_NONE:"CMDB_ATTR_CREATE_MODE_NONE",
        CMDB_ATTR_CREATE_MODE_OPEN:"CMDB_ATTR_CREATE_MODE_OPEN",
        CMDB_ATTR_CREATE_MODE_PROTECTED:"CMDB_ATTR_CREATE_MODE_PROTECTED",
    }
    cmdb_const['CMDB_RELATIONSHIP_DIRECTION'] = {
        CMDB_RELATIONSHIP_DIRECTION_OUT:"CMDB_RELATIONSHIP_DIRECTION_OUT",
        CMDB_RELATIONSHIP_DIRECTION_IN:"CMDB_RELATIONSHIP_DIRECTION_IN",
    }
    cmdb_const['CMDB_SYSTEM_INIT_LICENSE'] = {
        CMDB_SYSTEM_INIT_LICENSE_MODE:"CMDB_SYSTEM_INIT_LICENSE_MODE",
    }
    cmdb_const['CMDB_SORT'] = {
        CMDB_SORT_ASCENDING:"CMDB_SORT_ASCENDING",
        CMDB_SORT_DESCENDING:"CMDB_SORT_DESCENDING",
    }
    cmdb_const['CMDB_STRING_SEPARATOR'] = {
        CMDB_STRING_SEPARATOR:"CMDB_STRING_SEPARATOR",
    }
    cmdb_const['CMDB_GET_ATTR'] = {
        CMDB_GET_ATTR_NONE:"CMDB_GET_ATTR_NONE",
        CMDB_GET_ATTR_CUSTOM_LIST:"CMDB_GET_ATTR_CUSTOM_LIST",
        CMDB_GET_ATTR_NONHIDDEN:"CMDB_GET_ATTR_NONHIDDEN",
        CMDB_GET_ATTR_ALL:"CMDB_GET_ATTR_ALL",
    }
    cmdb_const['CMDB_QUALIFIER_TYPE'] = {
        CMDB_QUALIFIER_TYPE_NONE:"CMDB_QUALIFIER_TYPE_NONE",
        CMDB_QUALIFIER_TYPE_STRING:"CMDB_QUALIFIER_TYPE_STRING",
        CMDB_QUALIFIER_TYPE_STRUCT:"CMDB_QUALIFIER_TYPE_STRUCT",
    }
    cmdb_const['CMDB_WEAK'] = {
        CMDB_WEAK_RELATIONSHIP:"CMDB_WEAK_RELATIONSHIP",
        CMDB_WEAK_OBJECT:"CMDB_WEAK_OBJECT",
    }
    cmdb_const['CMDB_ERROR'] = {
        CMDB_ERROR_SYSTEM_NOT_INITIALIZED:"CMDB_ERROR_SYSTEM_NOT_INITIALIZED",
        CMDB_ERROR_SYSTEM_CANNOT_BE_INITIALIZED:"CMDB_ERROR_SYSTEM_CANNOT_BE_INITIALIZED",
        CMDB_ERROR_NO_SUCH_CLASS:"CMDB_ERROR_NO_SUCH_CLASS",
        CMDB_ERROR_REQUIRED_PARAM_EMPTY:"CMDB_ERROR_REQUIRED_PARAM_EMPTY",
        CMDB_ERROR_NO_SUCH_ATTRIBUTE:"CMDB_ERROR_NO_SUCH_ATTRIBUTE",
        CMDB_ERROR_UNSUPPORTED_ATTRIBUTE_DATA_TYPE:"CMDB_ERROR_UNSUPPORTED_ATTRIBUTE_DATA_TYPE",
        CMDB_ERROR_INSTANCE_NOT_FOUND:"CMDB_ERROR_INSTANCE_NOT_FOUND",
        CMDB_ERROR_SYSTEM_ERROR:"CMDB_ERROR_SYSTEM_ERROR",
        CMDB_ERROR_CLASS_NAME_ID_NOT_UNIQUE:"CMDB_ERROR_CLASS_NAME_ID_NOT_UNIQUE",
        CMDB_ERROR_CLASS_META_DATA_INVALID:"CMDB_ERROR_CLASS_META_DATA_INVALID",
        CMDB_ERROR_CLASS_ALREADY_EXISTS:"CMDB_ERROR_CLASS_ALREADY_EXISTS",
        CMDB_ERROR_CLASS_DOES_NOT_EXIST:"CMDB_ERROR_CLASS_DOES_NOT_EXIST",
        CMDB_ERROR_INVALID_ABSTRACT_CLASS:"CMDB_ERROR_INVALID_ABSTRACT_CLASS",
        CMDB_ERROR_ATTRIBUTE_NAME_NOT_UNIQUE:"CMDB_ERROR_ATTRIBUTE_NAME_NOT_UNIQUE",
        CMDB_ERROR_ATTRIBUTE_ALREADY_EXISTS:"CMDB_ERROR_ATTRIBUTE_ALREADY_EXISTS",
        CMDB_ERROR_INVALID_ENUM_DEFAULT:"CMDB_ERROR_INVALID_ENUM_DEFAULT",
        CMDB_ERROR_INVALID_LIST_FORMAT:"CMDB_ERROR_INVALID_LIST_FORMAT",
        CMDB_ERROR_EXCEED_MAX_LIST_ITEMS:"CMDB_ERROR_EXCEED_MAX_LIST_ITEMS",
        CMDB_ERROR_ROLE_NAMES_MUST_BE_DIFFERENT:"CMDB_ERROR_ROLE_NAMES_MUST_BE_DIFFERENT",
        CMDB_ERROR_INVALID_CARDINALITY_VALUE:"CMDB_ERROR_INVALID_CARDINALITY_VALUE",
        CMDB_ERROR_SUPERCLASS_MUST_BE_REL_CLASS:"CMDB_ERROR_SUPERCLASS_MUST_BE_REL_CLASS",
        CMDB_ERROR_ROLE_NAME_DOES_NOT_MATCH_SUPERCLASS:"CMDB_ERROR_ROLE_NAME_DOES_NOT_MATCH_SUPERCLASS",
        CMDB_ERROR_CLASS_ROLE_NOT_SUPERCLASS_DERIVED:"CMDB_ERROR_CLASS_ROLE_NOT_SUPERCLASS_DERIVED",
        CMDB_ERROR_SUBCLASS_CARDINALITY_LESS_RESTRICTIVE:"CMDB_ERROR_SUBCLASS_CARDINALITY_LESS_RESTRICTIVE",
        CMDB_ERROR_RELATIONSHIP_PARAM_CANNOT_BE_CHANGED:"CMDB_ERROR_RELATIONSHIP_PARAM_CANNOT_BE_CHANGED",
        CMDB_ERROR_INVALID_CLASS_TYPE:"CMDB_ERROR_INVALID_CLASS_TYPE",
        CMDB_ERROR_CLASS_TYPE_CANNOT_BE_CHANGED:"CMDB_ERROR_CLASS_TYPE_CANNOT_BE_CHANGED",
        CMDB_ERROR_ATTRIBUTE_CANNOT_BE_SET:"CMDB_ERROR_ATTRIBUTE_CANNOT_BE_SET",
        CMDB_ERROR_ATTRIBUTE_INFO_CORRUPT:"CMDB_ERROR_ATTRIBUTE_INFO_CORRUPT",
        CMDB_ERROR_INVALID_ABSTRACT_CLASS_INST_OPERATION:"CMDB_ERROR_INVALID_ABSTRACT_CLASS_INST_OPERATION",
        CMDB_ERROR_INVALID_CATEGORAIZATION_SUBCLASS:"CMDB_ERROR_INVALID_CATEGORAIZATION_SUBCLASS",
        CMDB_ERROR_INVALID_FINAL_CLASS:"CMDB_ERROR_INVALID_FINAL_CLASS",
        CMDB_ERROR_INVALID_SINGLETON_CLASS:"CMDB_ERROR_INVALID_SINGLETON_CLASS",
        CMDB_WARN_INVALID_EXPORT_ITEM_TYPE:"CMDB_WARN_INVALID_EXPORT_ITEM_TYPE",
        CMDB_ERROR_PERMISSION_LIST_INVALID:"CMDB_ERROR_PERMISSION_LIST_INVALID",
        CMDB_ERROR_QUERY_GRAPH_HAS_NO_STARTNODE:"CMDB_ERROR_QUERY_GRAPH_HAS_NO_STARTNODE",
        CMDB_ERROR_QUERY_GRAPH_HAS_AMBIGUOUS_NODE:"CMDB_ERROR_QUERY_GRAPH_HAS_AMBIGUOUS_NODE",
        CMDB_ERROR_INVALID_SINGLETON_CLASS_INST_OPERATION:"CMDB_ERROR_INVALID_SINGLETON_CLASS_INST_OPERATION",
        CMDB_ERROR_RELATION_CARDINALITY_CHECK:"CMDB_ERROR_RELATION_CARDINALITY_CHECK",
        CMDB_ERROR_RELATION_END_PT_DOES_NOT_EXIST:"CMDB_ERROR_RELATION_END_PT_DOES_NOT_EXIST",
        CMDB_ERROR_CATSUBCLASS_REQD_ATTR_NOT_ALLOWED:"CMDB_ERROR_CATSUBCLASS_REQD_ATTR_NOT_ALLOWED",
        CMDB_ERROR_SUBCLASS_MUST_BE_RS_WEAK_REFERENCE:"CMDB_ERROR_SUBCLASS_MUST_BE_RS_WEAK_REFERENCE",
        CMDB_ERROR_INVALID_CARDINALITY_FOR_WEAK_REFERENCE:"CMDB_ERROR_INVALID_CARDINALITY_FOR_WEAK_REFERENCE",
        CMDB_ERROR_WEAK_INSTANCE_ALREADY_ASSOCIATED:"CMDB_ERROR_WEAK_INSTANCE_ALREADY_ASSOCIATED",
        CMDB_ERROR_NO_WEAK_RELATION_ABSTRACT_CLASS_ALLOWED:"CMDB_ERROR_NO_WEAK_RELATION_ABSTRACT_CLASS_ALLOWED",
        CMDB_ERROR_SETTING_LEAD_CLASS_REF_DISALLOWED:"CMDB_ERROR_SETTING_LEAD_CLASS_REF_DISALLOWED",
        CMDB_ERROR_CANNOT_MODIFY_PRIMARY_KEY_ON_ATTRIBUTE:"CMDB_ERROR_CANNOT_MODIFY_PRIMARY_KEY_ON_ATTRIBUTE",
        CMDB_ERROR_PRIMARY_KEY_ISNT_UNIQUE:"CMDB_ERROR_PRIMARY_KEY_ISNT_UNIQUE",
        CMDB_ERROR_MORE_THAN_ONE_PRIMARY_KEY_DISALLOWED:"CMDB_ERROR_MORE_THAN_ONE_PRIMARY_KEY_DISALLOWED",
        CMDB_ERROR_NO_RHS_CATSUBCLASS_FOR_WEAK_REFERENCE:"CMDB_ERROR_NO_RHS_CATSUBCLASS_FOR_WEAK_REFERENCE",
        CMDB_ERROR_NO_SUCH_INDEX:"CMDB_ERROR_NO_SUCH_INDEX",
        CMDB_ERROR_DELETE_CLASS_FAILED_DATA_EXISTS:"CMDB_ERROR_DELETE_CLASS_FAILED_DATA_EXISTS",
        CMDB_ERROR_DELETE_CLASS_FAILED_DEPENDECIES_EXISTS:"CMDB_ERROR_DELETE_CLASS_FAILED_DEPENDECIES_EXISTS",
        CMDB_WARN_DELETE_CLASS_FAILED_DEP_REG_CLASS:"CMDB_WARN_DELETE_CLASS_FAILED_DEP_REG_CLASS",
        CMDB_WARN_DELETE_CLASS_FAILED_DEP_REL_CLASS:"CMDB_WARN_DELETE_CLASS_FAILED_DEP_REL_CLASS",
        CMDB_WARN_DELETE_CLASS_FAILED_DEP_WEAK_REF_CLASS:"CMDB_WARN_DELETE_CLASS_FAILED_DEP_WEAK_REF_CLASS",
        CMDB_ERROR_NO_SUCH_SOURCE_ATTRIBUTE_FOR_WEAK_REL:"CMDB_ERROR_NO_SUCH_SOURCE_ATTRIBUTE_FOR_WEAK_REL",
        CMDB_ERROR_NO_SUCH_TARGET_ATTRIBUTE_FOR_WEAK_REL:"CMDB_ERROR_NO_SUCH_TARGET_ATTRIBUTE_FOR_WEAK_REL",
        CMDB_ERROR_ATTRIBUTE_DATATYPE_MISMATCH_FOR_WEAK_REL:"CMDB_ERROR_ATTRIBUTE_DATATYPE_MISMATCH_FOR_WEAK_REL",
        CMDB_ERROR_TARGET_WEAK_ATTR_CANNOT_DERIVED_ATTR:"CMDB_ERROR_TARGET_WEAK_ATTR_CANNOT_DERIVED_ATTR",
        CMDB_ERROR_CATGORIZATION_SUB_PERM_LIST_INVALID:"CMDB_ERROR_CATGORIZATION_SUB_PERM_LIST_INVALID",
        CMDB_ERROR_INSTANCE_DELETE_ON_FORM_DISALLOWED:"CMDB_ERROR_INSTANCE_DELETE_ON_FORM_DISALLOWED",
        CMDB_ERROR_CREATE_GUID_FAILED:"CMDB_ERROR_CREATE_GUID_FAILED",
        CMDB_WARN_NO_SUCH_ATTACHMENT_POOL:"CMDB_WARN_NO_SUCH_ATTACHMENT_POOL",
        CMDB_ERROR_SYSTEM_INIT_LICENSE_MODE:"CMDB_ERROR_SYSTEM_INIT_LICENSE_MODE",
        CMDB_ERROR_IMPORT_ITEM_ITEM:"CMDB_ERROR_IMPORT_ITEM_ITEM",
        CMDB_ERROR_MISMATCHING_ATTR_DATATYPE:"CMDB_ERROR_MISMATCHING_ATTR_DATATYPE",
        CMDB_ERROR_ATTRIBUTE_VALUE_OUT_OF_LIMITS:"CMDB_ERROR_ATTRIBUTE_VALUE_OUT_OF_LIMITS",
        CMDB_ERROR_INVALID_INDEX_LIST:"CMDB_ERROR_INVALID_INDEX_LIST",
        CMDB_ERROR_SETTING_FORM_NAME_CHARAC_DISALLOWED:"CMDB_ERROR_SETTING_FORM_NAME_CHARAC_DISALLOWED",
        CMDB_ERROR_INVALID_DATATYPE_FOR_CLASS_CHARAC:"CMDB_ERROR_INVALID_DATATYPE_FOR_CLASS_CHARAC",
        CMDB_ERROR_NAMESPACE_NAME_TOO_LONG:"CMDB_ERROR_NAMESPACE_NAME_TOO_LONG",
        CMDB_ERROR_CLASS_NAME_TOO_LONG:"CMDB_ERROR_CLASS_NAME_TOO_LONG",
        CMDB_ERROR_SUBCLASS_SUPERCLASS_NAMESPACE_MISMATCH:"CMDB_ERROR_SUBCLASS_SUPERCLASS_NAMESPACE_MISMATCH",
        CMDB_ERROR_REQUIRED_ATTRIBUTE_VALUE_MISSING:"CMDB_ERROR_REQUIRED_ATTRIBUTE_VALUE_MISSING",
        CMDB_ERROR_MODIFY_NAMESPACE_NAME_IS_DISALLOWED:"CMDB_ERROR_MODIFY_NAMESPACE_NAME_IS_DISALLOWED",
        CMDB_ERROR_CHARACTER_DISALLOWED_IN_NAME:"CMDB_ERROR_CHARACTER_DISALLOWED_IN_NAME",
        CMDB_ERROR_ATTRIBUTE_NAME_TOO_LONG:"CMDB_ERROR_ATTRIBUTE_NAME_TOO_LONG",
        CMDB_ERROR_INVALID_ATTRIBUTE_ENTRY_MODE:"CMDB_ERROR_INVALID_ATTRIBUTE_ENTRY_MODE",
        CMDB_ERROR_ATTR_FIELD_ID_NOT_UNIQUE:"CMDB_ERROR_ATTR_FIELD_ID_NOT_UNIQUE",
        CMDB_ERROR_INVALID_DATATYPE_FOR_ATTR_CHARAC:"CMDB_ERROR_INVALID_DATATYPE_FOR_ATTR_CHARAC",
        CMDB_ERROR_SETTING_PRIMARY_KEY_CHARAC_DISALLOWED:"CMDB_ERROR_SETTING_PRIMARY_KEY_CHARAC_DISALLOWED",
        CMDB_ERROR_SETTING_PROP_OWNER_CHARAC_DISALLOWED:"CMDB_ERROR_SETTING_PROP_OWNER_CHARAC_DISALLOWED",
        CMDB_ERROR_REL_END_POINT_CLASS_NAMESPACE_MISMATCH:"CMDB_ERROR_REL_END_POINT_CLASS_NAMESPACE_MISMATCH",
        CMDB_ERROR_ENUM_NAME_INVALID:"CMDB_ERROR_ENUM_NAME_INVALID",
        CMDB_ERROR_ATTRIBUTE_ID_NOT_UNIQUE:"CMDB_ERROR_ATTRIBUTE_ID_NOT_UNIQUE",
        CMDB_ERROR_INVALID_ATTR_LIMIT_DATA_TYPE:"CMDB_ERROR_INVALID_ATTR_LIMIT_DATA_TYPE",
        CMDB_ERROR_NO_ACCESS_TO_CLASS:"CMDB_ERROR_NO_ACCESS_TO_CLASS",
        CMDB_ERROR_NO_ACCESS_TO_ATTRIBUTE:"CMDB_ERROR_NO_ACCESS_TO_ATTRIBUTE",
        CMDB_ERROR_OS_SYSTEM_USER_DOES_NOT_EXIST:"CMDB_ERROR_OS_SYSTEM_USER_DOES_NOT_EXIST",
        CMDB_ERROR_DATASET_ID_RECON_ID_NOT_UNIQUE:"CMDB_ERROR_DATASET_ID_RECON_ID_NOT_UNIQUE",
        CMDB_ERROR_INVALID_CLASS_ID:"CMDB_ERROR_INVALID_CLASS_ID",
        CMDB_ERROR_QUERY_GRAPH_INVALID_DIRECTION:"CMDB_ERROR_QUERY_GRAPH_INVALID_DIRECTION",
        CMDB_ERROR_CURRENT_API_IS_DEPRECATED:"CMDB_ERROR_CURRENT_API_IS_DEPRECATED",
        CMDB_WARN_IMPORT_INST_SKIPPED:"CMDB_WARN_IMPORT_INST_SKIPPED",
        CMDB_INFO_IMPORT_INST_SUMMARY:"CMDB_INFO_IMPORT_INST_SUMMARY",
        CMDB_ERROR_INVALID_DELETE_OPTION:"CMDB_ERROR_INVALID_DELETE_OPTION",
        CMDB_ERROR_INVALID_META_DATA_STATUS:"CMDB_ERROR_INVALID_META_DATA_STATUS",
        CMDB_ERROR_INVALID_REL_ENDPOINT_CLASS_ID:"CMDB_ERROR_INVALID_REL_ENDPOINT_CLASS_ID",
        CMDB_ERROR_ACCESS_TLS_BLOCK_FAILED:"CMDB_ERROR_ACCESS_TLS_BLOCK_FAILED",
        CMDB_ERROR_UNRECOGNIZED_VERSION_PATCH_STRING:"CMDB_ERROR_UNRECOGNIZED_VERSION_PATCH_STRING",
        CMDB_ERROR_INVALID_CASCADE_DELETE_VALUE:"CMDB_ERROR_INVALID_CASCADE_DELETE_VALUE",
    }
    cmdb_const['rest'] = {
        CMDB_ITEM_TYPE_META_DATA:"CMDB_ITEM_TYPE_META_DATA",
        CMDB_ITEM_TYPE_INSTANCE_DATA:"CMDB_ITEM_TYPE_INSTANCE_DATA",
    }
    cmdb_const['CMDB_EXPORT_OPTION'] = {
        CMDB_EXPORT_OPTION_NONE:"CMDB_EXPORT_OPTION_NONE",
        CMDB_EXPORT_OPTION_CLASS_ONLY:"CMDB_EXPORT_OPTION_CLASS_ONLY",
        CMDB_EXPORT_OPTION_SUPER_CLASSES:"CMDB_EXPORT_OPTION_SUPER_CLASSES",
        CMDB_EXPORT_OPTION_SUB_CLASSES:"CMDB_EXPORT_OPTION_SUB_CLASSES",
    }
    cmdb_const['AR_GUID_BUF'] = {
        AR_GUID_BUF_LEN:"AR_GUID_BUF_LEN",
    }
    cmdb_const['CMDB_LOC'] = {
        CMDB_LOC_NULL:"CMDB_LOC_NULL",
        CMDB_LOC_FILENAME:"CMDB_LOC_FILENAME",
        CMDB_LOC_BUFFER:"CMDB_LOC_BUFFER",
    }
    cmdb_const['CMDB_VER'] = {
        CMDB_VER_MAJOR:"CMDB_VER_MAJOR",
        CMDB_VER_MINOR:"CMDB_VER_MINOR",
        CMDB_VER_MAINTENANCE:"CMDB_VER_MAINTENANCE",
        CMDB_VER_PATCH:"CMDB_VER_PATCH"
        }
    cmdb_const['rest'] = {
        CMDB_START_WITH_FIRST_INSTANCE:"CMDB_START_WITH_FIRST_INSTANCE",
        CMDB_NO_MAX_LIST_RETRIEVE:"CMDB_NO_MAX_LIST_RETRIEVE",
        CMDB_EXPORT_FORMAT_XML:"CMDB_EXPORT_FORMAT_XML",
        CMDB_RESERV_TYPE_MGMT_META_DATA_RECORD_STATUS:"CMDB_RESERV_TYPE_MGMT_META_DATA_RECORD_STATUS",
    }

if cmdbversion in ['cmdbapi20']:
    cmdb_const['CMDB_ATTR_CHARAC'].update({
    CMDB_ATTR_CHARAC_AUDIT_OPTION:"CMDB_ATTR_CHARAC_AUDIT_OPTION",
    CMDB_ATTR_CHARAC_NAMESPACE:"CMDB_ATTR_CHARAC_NAMESPACE"
                         })
    cmdb_const['CMDB_ATTR_ID'].update({
    CMDB_ATTR_ID_ACCOUNT_ID:"CMDB_ATTR_ID_ACCOUNT_ID",
    CMDB_ATTR_ID_ATTR_DATA_SOURCE_LIST:"CMDB_ATTR_ID_ATTR_DATA_SOURCE_LIST",
#     CMDB_ATTR_ID_AUDIT_ID:"CMDB_ATTR_ID_AUDIT_ID",
#     CMDB_ATTR_ID_AUDIT_QUAL_RESULT:"CMDB_ATTR_ID_AUDIT_QUAL_RESULT",
    CMDB_ATTR_ID_COMPARE_ACTION_CODE:"CMDB_ATTR_ID_COMPARE_ACTION_CODE",
    CMDB_ATTR_ID_DATASET_ACCESSIBILITY:"CMDB_ATTR_ID_DATASET_ACCESSIBILITY",
    CMDB_ATTR_ID_DATASET_CLIENT_TYPE_LIST:"CMDB_ATTR_ID_DATASET_CLIENT_TYPE_LIST",
    CMDB_ATTR_ID_DATASET_DATASET_TYPE:"CMDB_ATTR_ID_DATASET_DATASET_TYPE",
    CMDB_ATTR_ID_DATASET_ID:"CMDB_ATTR_ID_DATASET_ID",
    CMDB_ATTR_ID_DATASET_NAME:"CMDB_ATTR_ID_DATASET_NAME",
    CMDB_ATTR_ID_DATASET_SOURCE_DATASET_ID:"CMDB_ATTR_ID_DATASET_SOURCE_DATASET_ID",
#     CMDB_ATTR_ID_DELETED_IN_OVERLAY:"CMDB_ATTR_ID_DELETED_IN_OVERLAY",
    CMDB_ATTR_ID_LAST_REJOBRUN_ID:"CMDB_ATTR_ID_LAST_REJOBRUN_ID",
    CMDB_ATTR_ID_ROW_LEVEL_SECURITY:"CMDB_ATTR_ID_ROW_LEVEL_SECURITY",
    CMDB_ATTR_ID_UICOMP_COMP_ATTACH:"CMDB_ATTR_ID_UICOMP_COMP_ATTACH",
    CMDB_ATTR_ID_UICOMP_COMP_CLSID:"CMDB_ATTR_ID_UICOMP_COMP_CLSID",
    CMDB_ATTR_ID_UICOMP_COMP_LOCALE:"CMDB_ATTR_ID_UICOMP_COMP_LOCALE",
    CMDB_ATTR_ID_UICOMP_COMP_NAME:"CMDB_ATTR_ID_UICOMP_COMP_NAME",
    CMDB_ATTR_ID_UICOMP_COMP_QUAL:"CMDB_ATTR_ID_UICOMP_COMP_QUAL",
    CMDB_ATTR_ID_UICOMP_COMP_STR:"CMDB_ATTR_ID_UICOMP_COMP_STR",
    CMDB_ATTR_ID_UICOMP_COMP_TAG1:"CMDB_ATTR_ID_UICOMP_COMP_TAG1",
    CMDB_ATTR_ID_UICOMP_COMP_TAG2:"CMDB_ATTR_ID_UICOMP_COMP_TAG2",
    CMDB_ATTR_ID_UICOMP_COMP_TAG3:"CMDB_ATTR_ID_UICOMP_COMP_TAG3",
    CMDB_ATTR_ID_UICOMP_COMP_TAG4:"CMDB_ATTR_ID_UICOMP_COMP_TAG4",
    CMDB_ATTR_ID_UICOMP_COMP_TAG5:"CMDB_ATTR_ID_UICOMP_COMP_TAG5",
    CMDB_ATTR_ID_UICOMP_COMP_TYPE:"CMDB_ATTR_ID_UICOMP_COMP_TYPE",
    CMDB_ATTR_ID_WRITE_SECURITY:"CMDB_ATTR_ID_WRITE_SECURITY",
#    CMDB_ATTR_ID_Z_TMP_INTEGER_9:"CMDB_ATTR_ID_Z_TMP_INTEGER_9"
    })
    cmdb_const['CMDB_ATTR_ID_FEDERATED_DATA'] = {
    CMDB_ATTR_ID_FEDERATED_DATA_AR_ACCESS_METHOD:"CMDB_ATTR_ID_FEDERATED_DATA_AR_ACCESS_METHOD",
    CMDB_ATTR_ID_FEDERATED_DATA_AR_FORM_NAME:"CMDB_ATTR_ID_FEDERATED_DATA_AR_FORM_NAME",
    CMDB_ATTR_ID_FEDERATED_DATA_AR_QUERY:"CMDB_ATTR_ID_FEDERATED_DATA_AR_QUERY",
    CMDB_ATTR_ID_FEDERATED_DATA_AR_SERVER_NAME:"CMDB_ATTR_ID_FEDERATED_DATA_AR_SERVER_NAME",
    CMDB_ATTR_ID_FEDERATED_DATA_AR_VIEW_NAME:"CMDB_ATTR_ID_FEDERATED_DATA_AR_VIEW_NAME",
    CMDB_ATTR_ID_FEDERATED_DATA_DATA_SOURCE:"CMDB_ATTR_ID_FEDERATED_DATA_DATA_SOURCE",
    CMDB_ATTR_ID_FEDERATED_DATA_FEDERATION_ACCESS_METHOD:"CMDB_ATTR_ID_FEDERATED_DATA_FEDERATION_ACCESS_METHOD",
    CMDB_ATTR_ID_FEDERATED_DATA_FEDERATION_ACCESS_STRING:"CMDB_ATTR_ID_FEDERATED_DATA_FEDERATION_ACCESS_STRING",
    CMDB_ATTR_ID_FEDERATED_DATA_FEDERATION_ACTION_TYPE:"CMDB_ATTR_ID_FEDERATED_DATA_FEDERATION_ACTION_TYPE",
    CMDB_ATTR_ID_FEDERATED_DATA_NAME:"CMDB_ATTR_ID_FEDERATED_DATA_NAME",
    CMDB_ATTR_ID_FEDERATED_DATA_RESULT10:"CMDB_ATTR_ID_FEDERATED_DATA_RESULT10",
    CMDB_ATTR_ID_FEDERATED_DATA_RESULT1:"CMDB_ATTR_ID_FEDERATED_DATA_RESULT1",
    CMDB_ATTR_ID_FEDERATED_DATA_RESULT2:"CMDB_ATTR_ID_FEDERATED_DATA_RESULT2",
    CMDB_ATTR_ID_FEDERATED_DATA_RESULT3:"CMDB_ATTR_ID_FEDERATED_DATA_RESULT3",
    CMDB_ATTR_ID_FEDERATED_DATA_RESULT4:"CMDB_ATTR_ID_FEDERATED_DATA_RESULT4",
    CMDB_ATTR_ID_FEDERATED_DATA_RESULT5:"CMDB_ATTR_ID_FEDERATED_DATA_RESULT5",
    CMDB_ATTR_ID_FEDERATED_DATA_RESULT6:"CMDB_ATTR_ID_FEDERATED_DATA_RESULT6",
    CMDB_ATTR_ID_FEDERATED_DATA_RESULT7:"CMDB_ATTR_ID_FEDERATED_DATA_RESULT7",
    CMDB_ATTR_ID_FEDERATED_DATA_RESULT8:"CMDB_ATTR_ID_FEDERATED_DATA_RESULT8",
    CMDB_ATTR_ID_FEDERATED_DATA_RESULT9:"CMDB_ATTR_ID_FEDERATED_DATA_RESULT9",
    }
    cmdb_const['CMDB_ATTR_ID_FEDERATED_LINK'] = {
    CMDB_ATTR_ID_FEDERATED_LINK_METHOD:"CMDB_ATTR_ID_FEDERATED_LINK_METHOD",
    CMDB_ATTR_ID_FEDERATED_LINK_QUERY:"CMDB_ATTR_ID_FEDERATED_LINK_QUERY"
    }
    cmdb_const['CMDB_ATTR_ENUM_STYLE'] = {
    CMDB_ATTR_ENUM_STYLE_CUSTOM:"CMDB_ATTR_ENUM_STYLE_CUSTOM",
    CMDB_ATTR_ENUM_STYLE_REGULAR:"CMDB_ATTR_ENUM_STYLE_REGULAR"
    }
    cmdb_const['CMDB_ATTR_ID'].update({
    })
    cmdb_const['CMDB_CLASS_AUDITTYPE'] = {
    CMDB_CLASS_AUDITTYPE_COPY:"CMDB_CLASS_AUDITTYPE_COPY",
    CMDB_CLASS_AUDITTYPE_LOG:"CMDB_CLASS_AUDITTYPE_LOG",
    CMDB_CLASS_AUDITTYPE_NONE:"CMDB_CLASS_AUDITTYPE_NONE",
    }
    cmdb_const['CMDB_CLASS_CHARAC'].update({
    CMDB_CLASS_CHARAC_AUDIT_FORM:"CMDB_CLASS_CHARAC_AUDIT_FORM",
    CMDB_CLASS_CHARAC_EXPOSURE:"CMDB_CLASS_CHARAC_EXPOSURE"
    })
    cmdb_const['CMDB_CLASS_EXPOSURE'] = {
    CMDB_CLASS_EXPOSURE_NONE:"CMDB_CLASS_EXPOSURE_NONE",
    CMDB_CLASS_EXPOSURE_USED_HIDDEN:"CMDB_CLASS_EXPOSURE_USED_HIDDEN",
    CMDB_CLASS_EXPOSURE_USED_VISIBLE:"CMDB_CLASS_EXPOSURE_USED_VISIBLE"
    }
    cmdb_const['CMDB_CLASS_TYPE_FEDERATION'] = {
    CMDB_CLASS_TYPE_FEDERATION_DATA:"CMDB_CLASS_TYPE_FEDERATION_DATA",
    CMDB_CLASS_TYPE_FEDERATION_RELATIONSHIP:"CMDB_CLASS_TYPE_FEDERATION_RELATIONSHIP"
    }
    cmdb_const['CMDB_COMPONENT_TYPE'] = {
    CMDB_COMPONENT_TYPE_ICON:"CMDB_COMPONENT_TYPE_ICON",
    CMDB_COMPONENT_TYPE_LINE:"CMDB_COMPONENT_TYPE_LINE",
    CMDB_COMPONENT_TYPE_LOCALIZED_LABEL:"CMDB_COMPONENT_TYPE_LOCALIZED_LABEL",
    CMDB_COMPONENT_TYPE_NONE:"CMDB_COMPONENT_TYPE_NONE",
    CMDB_COMPONENT_TYPE_TOOLTIP:"CMDB_COMPONENT_TYPE_TOOLTIP"
    }
    
    cmdb_const['CMDB_DATASET_ACCESSIBILITY'] = {
    CMDB_DATASET_ACCESSIBILITY_READ_ONLY:"CMDB_DATASET_ACCESSIBILITY_READ_ONLY",
    CMDB_DATASET_ACCESSIBILITY_WRITABLE:"CMDB_DATASET_ACCESSIBILITY_WRITABLE",
    CMDB_DATASET_ACCESSIBLITY_WRITABLE_BY_CLIENT_TYPE:"CMDB_DATASET_ACCESSIBLITY_WRITABLE_BY_CLIENT_TYPE"
    }
    cmdb_const['CMDB_DATASET_TYPE'] = {
    CMDB_DATASET_TYPE_OVERLAY:"CMDB_DATASET_TYPE_OVERLAY",
    CMDB_DATASET_TYPE_REGULAR:"CMDB_DATASET_TYPE_REGULAR"
    }
    cmdb_const['CMDB_ERROR'].update({
    CMDB_ERROR_BULK_TRAN_ALREADY_BEGUN:"CMDB_ERROR_BULK_TRAN_ALREADY_BEGUN",
    CMDB_ERROR_BULK_TRAN_API_SESSION_ID_BAD:"CMDB_ERROR_BULK_TRAN_API_SESSION_ID_BAD",
    CMDB_ERROR_BULK_TRAN_NOT_BEGUN:"CMDB_ERROR_BULK_TRAN_NOT_BEGUN",
#    CMDB_ERROR_DATASET_ID_MISSING:"CMDB_ERROR_DATASET_ID_MISSING",
    CMDB_ERROR_DATASET_NO_PROPER_ACCESS:"CMDB_ERROR_DATASET_NO_PROPER_ACCESS",
    CMDB_ERROR_DATASET_OVERLAY_SOURCE_MISSING:"CMDB_ERROR_DATASET_OVERLAY_SOURCE_MISSING",
#    CMDB_ERROR_DATASET_TYPE_MISMATCH:"CMDB_ERROR_DATASET_TYPE_MISMATCH",
    CMDB_ERROR_DATASET_UNDERLAY_INTERNAL_ERROR:"CMDB_ERROR_DATASET_UNDERLAY_INTERNAL_ERROR",
    CMDB_ERROR_DUPLICATE_INDEX:"CMDB_ERROR_DUPLICATE_INDEX",
    CMDB_ERROR_ENUM_ID_INVALID:"CMDB_ERROR_ENUM_ID_INVALID",
    CMDB_ERROR_ENUM_ID_VALUE_LEN_MISMATCH:"CMDB_ERROR_ENUM_ID_VALUE_LEN_MISMATCH",
    CMDB_ERROR_FEDLINK_LAUNCH_FAILED:"CMDB_ERROR_FEDLINK_LAUNCH_FAILED",
    CMDB_ERROR_INVALID_AUDIT_COPY_TYPE:"CMDB_ERROR_INVALID_AUDIT_COPY_TYPE",
    CMDB_ERROR_INVALID_AUDIT_LOG_TYPE:"CMDB_ERROR_INVALID_AUDIT_LOG_TYPE",
    CMDB_ERROR_INVALID_DATASET_ID:"CMDB_ERROR_INVALID_DATASET_ID",
    CMDB_ERROR_NO_SUCH_DATASET:"CMDB_ERROR_NO_SUCH_DATASET",
    CMDB_WARNING_DATASET_CACHE_LOADING:"CMDB_WARNING_DATASET_CACHE_LOADING",
    CMDB_WARNING_FOREIGN_KEY_EXPAND_FAILED:"CMDB_WARNING_FOREIGN_KEY_EXPAND_FAILED",

    })
    cmdb_const['CMDB_FEDERATED_ACCESS_TYPE'] = {
    CMDB_FEDERATED_ACCESS_TYPE_AR:"CMDB_FEDERATED_ACCESS_TYPE_AR",
    CMDB_FEDERATED_ACCESS_TYPE_AR_PROCESS:"CMDB_FEDERATED_ACCESS_TYPE_AR_PROCESS",
    CMDB_FEDERATED_ACCESS_TYPE_AR_URL:"CMDB_FEDERATED_ACCESS_TYPE_AR_URL",
    CMDB_FEDERATED_ACCESS_TYPE_DATA_STORE:"CMDB_FEDERATED_ACCESS_TYPE_DATA_STORE",
    CMDB_FEDERATED_ACCESS_TYPE_MANUAL:"CMDB_FEDERATED_ACCESS_TYPE_MANUAL",
    # CMDB_FEDERATED_ACCESS_TYPE_NONE:"CMDB_FEDERATED_ACCESS_TYPE_NONE",
    CMDB_FEDERATED_ACCESS_TYPE_PROCESS:"CMDB_FEDERATED_ACCESS_TYPE_PROCESS",
    CMDB_FEDERATED_ACCESS_TYPE_URL:"CMDB_FEDERATED_ACCESS_TYPE_URL",
    CMDB_FEDERATED_ACCESS_TYPE_WEBSERVICE:"CMDB_FEDERATED_ACCESS_TYPE_WEBSERVICE"
    }
    cmdb_const['CMDB_FEDERATED_ACTION'] = {
    CMDB_FEDERATED_ACTION_DATA_RETURN:"CMDB_FEDERATED_ACTION_DATA_RETURN",
    CMDB_FEDERATED_ACTION_LAUNCH:"CMDB_FEDERATED_ACTION_LAUNCH"
    }
    cmdb_const['CMDB_FEDERATED_LINK_TYPE'] = {
    CMDB_FEDERATED_LINK_TYPE_CLASS:"CMDB_FEDERATED_LINK_TYPE_CLASS",
    CMDB_FEDERATED_LINK_TYPE_INSTANCE:"CMDB_FEDERATED_LINK_TYPE_INSTANCE",
    }
    cmdb_const['CMDB_FEDERATION_ACTIVATION'] = {
    CMDB_FEDERATION_ACTIVATION_EXPAND:"CMDB_FEDERATION_ACTIVATION_EXPAND",
    CMDB_FEDERATION_ACTIVATION_LAUNCH:"CMDB_FEDERATION_ACTIVATION_LAUNCH",
    CMDB_FEDERATION_ACTIVATION_NONE:"CMDB_FEDERATION_ACTIVATION_NONE"
    }
    cmdb_const['CMDB_GROUP'] = {
    CMDB_GROUP_DATA_ADMIN_GROUP:"CMDB_GROUP_DATA_ADMIN_GROUP",
    CMDB_GROUP_DATA_VIEWER_GROUP:"CMDB_GROUP_DATA_VIEWER_GROUP",
    CMDB_GROUP_ROW_LEVEL_SECURITY:"CMDB_GROUP_ROW_LEVEL_SECURITY",
    CMDB_GROUP_WRITE_SECURITY:"CMDB_GROUP_WRITE_SECURITY"
    }
    cmdb_const['CMDB_RESERV_ATTR'].update({
    CMDB_RESERV_ATTR_AUDIT_TYPE:"CMDB_RESERV_ATTR_AUDIT_TYPE",
    CMDB_RESERV_ATTR_ENUM_CUST_ID:"CMDB_RESERV_ATTR_ENUM_CUST_ID",
    CMDB_RESERV_ATTR_ENUM_STYLE:"CMDB_RESERV_ATTR_ENUM_STYLE",
    CMDB_RESERV_ATTR_NAMESPACE:"CMDB_RESERV_ATTR_NAMESPACE",
    })
    cmdb_const['CMDB_RESERV_CLASS'].update({
    CMDB_RESERV_CLASS_AUDIT_FORM:"CMDB_RESERV_CLASS_AUDIT_FORM",
    CMDB_RESERV_CLASS_AUDIT_LOG_FORM:"CMDB_RESERV_CLASS_AUDIT_LOG_FORM",
#    CMDB_RESERV_CLASS_AUDIT_QUAL_RESULT:"CMDB_RESERV_CLASS_AUDIT_QUAL_RESULT",
    CMDB_RESERV_CLASS_AUDIT_QUAL_SER:"CMDB_RESERV_CLASS_AUDIT_QUAL_SER",
    CMDB_RESERV_CLASS_AUDIT_TYPE:"CMDB_RESERV_CLASS_AUDIT_TYPE",
    CMDB_RESERV_CLASS_EXPOSURE:"CMDB_RESERV_CLASS_EXPOSURE",
    })
    cmdb_const['CMDB_RESERV_DATASET'] = {
    CMDB_RESERV_DATASET_ACCESSIBILITY:"CMDB_RESERV_DATASET_ACCESSIBILITY",
    CMDB_RESERV_DATASET_CLIENT_TYPE_LIST:"CMDB_RESERV_DATASET_CLIENT_TYPE_LIST",
    CMDB_RESERV_DATASET_DATASET_TYPE:"CMDB_RESERV_DATASET_DATASET_TYPE",
    CMDB_RESERV_DATASET_ID:"CMDB_RESERV_DATASET_ID",
    CMDB_RESERV_DATASET_NAME:"CMDB_RESERV_DATASET_NAME",
    CMDB_RESERV_DATASET_SOURCE_DATASET_ID:"CMDB_RESERV_DATASET_SOURCE_DATASET_ID"
    }
    cmdb_const['CMDB_RESERV_FEDERATED'] = {
    CMDB_RESERV_FEDERATED_DATA_AR_ACCESS_METHOD:"CMDB_RESERV_FEDERATED_DATA_AR_ACCESS_METHOD",
    CMDB_RESERV_FEDERATED_DATA_AR_FORM_NAME:"CMDB_RESERV_FEDERATED_DATA_AR_FORM_NAME",
    CMDB_RESERV_FEDERATED_DATA_AR_QUERY:"CMDB_RESERV_FEDERATED_DATA_AR_QUERY",
    CMDB_RESERV_FEDERATED_DATA_AR_SERVER_NAME:"CMDB_RESERV_FEDERATED_DATA_AR_SERVER_NAME",
    CMDB_RESERV_FEDERATED_DATA_AR_VIEW_NAME:"CMDB_RESERV_FEDERATED_DATA_AR_VIEW_NAME",
    CMDB_RESERV_FEDERATED_DATA_DATA_SOURCE:"CMDB_RESERV_FEDERATED_DATA_DATA_SOURCE",
    CMDB_RESERV_FEDERATED_DATA_FEDERATION_ACCESS_METHOD:"CMDB_RESERV_FEDERATED_DATA_FEDERATION_ACCESS_METHOD",
    CMDB_RESERV_FEDERATED_DATA_FEDERATION_ACCESS_STRING:"CMDB_RESERV_FEDERATED_DATA_FEDERATION_ACCESS_STRING",
    CMDB_RESERV_FEDERATED_DATA_FEDERATION_ACTION_TYPE:"CMDB_RESERV_FEDERATED_DATA_FEDERATION_ACTION_TYPE",
    CMDB_RESERV_FEDERATED_DATA_NAME:"CMDB_RESERV_FEDERATED_DATA_NAME",
    CMDB_RESERV_FEDERATED_DATA_RESULT10:"CMDB_RESERV_FEDERATED_DATA_RESULT10",
    CMDB_RESERV_FEDERATED_DATA_RESULT1:"CMDB_RESERV_FEDERATED_DATA_RESULT1",
    CMDB_RESERV_FEDERATED_DATA_RESULT2:"CMDB_RESERV_FEDERATED_DATA_RESULT2",
    CMDB_RESERV_FEDERATED_DATA_RESULT3:"CMDB_RESERV_FEDERATED_DATA_RESULT3",
    CMDB_RESERV_FEDERATED_DATA_RESULT4:"CMDB_RESERV_FEDERATED_DATA_RESULT4",
    CMDB_RESERV_FEDERATED_DATA_RESULT5:"CMDB_RESERV_FEDERATED_DATA_RESULT5",
    CMDB_RESERV_FEDERATED_DATA_RESULT6:"CMDB_RESERV_FEDERATED_DATA_RESULT6",
    CMDB_RESERV_FEDERATED_DATA_RESULT7:"CMDB_RESERV_FEDERATED_DATA_RESULT7",
    CMDB_RESERV_FEDERATED_DATA_RESULT8:"CMDB_RESERV_FEDERATED_DATA_RESULT8",
    CMDB_RESERV_FEDERATED_DATA_RESULT9:"CMDB_RESERV_FEDERATED_DATA_RESULT9",
    CMDB_RESERV_FEDERATED_KEYLINK_PRODUCT_KEY:"CMDB_RESERV_FEDERATED_KEYLINK_PRODUCT_KEY",
    CMDB_RESERV_FEDERATED_LINK_LINK_METHOD:"CMDB_RESERV_FEDERATED_LINK_LINK_METHOD",
    CMDB_RESERV_FEDERATED_LINK_LINK_QUERY:"CMDB_RESERV_FEDERATED_LINK_LINK_QUERY"
    }
    cmdb_const['CMDB_RESERV_INSTANCE'].update({
    CMDB_RESERV_INSTANCE_ACCOUNT_ID:"CMDB_RESERV_INSTANCE_ACCOUNT_ID",
    CMDB_RESERV_INSTANCE_ATTR_DATA_SOURCE_LIST:"CMDB_RESERV_INSTANCE_ATTR_DATA_SOURCE_LIST",
    # CMDB_RESERV_INSTANCE_AUDIT_ID:"CMDB_RESERV_INSTANCE_AUDIT_ID",
    CMDB_RESERV_INSTANCE_COMPARE_ACTION_CODE:"CMDB_RESERV_INSTANCE_COMPARE_ACTION_CODE",
#    CMDB_RESERV_INSTANCE_DELETED_IN_OVERLAY:"CMDB_RESERV_INSTANCE_DELETED_IN_OVERLAY",
    CMDB_RESERV_INSTANCE_LAST_REJOBRUN_ID:"CMDB_RESERV_INSTANCE_LAST_REJOBRUN_ID",
    CMDB_RESERV_INSTANCE_ROW_LEVEL_SECURITY:"CMDB_RESERV_INSTANCE_ROW_LEVEL_SECURITY",
    CMDB_RESERV_INSTANCE_WRITE_SECURITY:"CMDB_RESERV_INSTANCE_WRITE_SECURITY",
#    CMDB_RESERV_INSTANCE_Z_TMP_INTEGER_9:"CMDB_RESERV_INSTANCE_Z_TMP_INTEGER_9"
    })
    cmdb_const['CMDB_RESERV_SHARED_APP_PROPERTIES'].update({
    CMDB_RESERV_SHARED_APP_PROPERTIES_APPNAME:"CMDB_RESERV_SHARED_APP_PROPERTIES_APPNAME"
    })
    cmdb_const['CMDB_RESERV_UICOMP'] = {
    CMDB_RESERV_UICOMP_ATTACHMENT:"CMDB_RESERV_UICOMP_ATTACHMENT"
    }
    cmdb_const['CMDB_ROLE'] = {
#    CMDB_ROLE_DATA_ADMIN:"CMDB_ROLE_DATA_ADMIN",
#    CMDB_ROLE_DATA_SUPER_ADMIN:"CMDB_ROLE_DATA_SUPER_ADMIN",
#    CMDB_ROLE_DATA_VIEWER:"CMDB_ROLE_DATA_VIEWER",
    CMDB_ROLE_DEFINITIONS_ADMIN:"CMDB_ROLE_DEFINITIONS_ADMIN",
    CMDB_ROLE_DEFINITIONS_VIEWER:"CMDB_ROLE_DEFINITIONS_VIEWER",
#    CMDB_ROLE_FEDERATION_ADMIN:"CMDB_ROLE_FEDERATION_ADMIN",
#    CMDB_ROLE_FEDERATION_USER:"CMDB_ROLE_FEDERATION_USER",
    CMDB_ROLE_RE_ADMIN:"CMDB_ROLE_RE_ADMIN",
    CMDB_ROLE_RE_USER:"CMDB_ROLE_RE_USER"
    }
    cmdb_const['CMDB_VER'].update({
    CMDB_VER_APP_ID_CMDB:"CMDB_VER_APP_ID_CMDB",
    CMDB_VER_APP_ID_RECON_ENG:"CMDB_VER_APP_ID_RECON_ENG",
    })
    cmdb_const['CMDBRE_ERROR'] = {
    CMDBRE_ERROR_CANCEL_JOB_RUN_FAILED:"CMDBRE_ERROR_CANCEL_JOB_RUN_FAILED",
    CMDBRE_ERROR_GETTING_JOBRUNID:"CMDBRE_ERROR_GETTING_JOBRUNID",
    CMDBRE_ERROR_INACTIVE_JOB_START:"CMDBRE_ERROR_INACTIVE_JOB_START",
    CMDBRE_ERROR_JOB_ALREADY_QUEUED:"CMDBRE_ERROR_JOB_ALREADY_QUEUED",
    CMDBRE_ERROR_JOB_ALREADY_RUN:"CMDBRE_ERROR_JOB_ALREADY_RUN",
    CMDBRE_ERROR_JOB_LOOKUP:"CMDBRE_ERROR_JOB_LOOKUP",
    CMDBRE_ERROR_JOB_NOT_EXIST:"CMDBRE_ERROR_JOB_NOT_EXIST",
    CMDBRE_ERROR_JOB_NOT_RUNNING:"CMDBRE_ERROR_JOB_NOT_RUNNING",
    CMDBRE_ERROR_START_JOB_RUN_FAILED:"CMDBRE_ERROR_START_JOB_RUN_FAILED"
    }
    cmdb_const['CMDBRE_ERROR'] = {
    CMDBRE_JOB_RUN_STATUS_ABORTED:"CMDBRE_JOB_RUN_STATUS_ABORTED",
    CMDBRE_JOB_RUN_STATUS_CANCELED:"CMDBRE_JOB_RUN_STATUS_CANCELED",
    CMDBRE_JOB_RUN_STATUS_FAILED:"CMDBRE_JOB_RUN_STATUS_FAILED",
    CMDBRE_JOB_RUN_STATUS_PAUSED:"CMDBRE_JOB_RUN_STATUS_PAUSED",
    CMDBRE_JOB_RUN_STATUS_QUEUED:"CMDBRE_JOB_RUN_STATUS_QUEUED",
    CMDBRE_JOB_RUN_STATUS_STARTED:"CMDBRE_JOB_RUN_STATUS_STARTED",
    CMDBRE_JOB_RUN_STATUS_SUCCESS:"CMDBRE_JOB_RUN_STATUS_SUCCESS",
    CMDBRE_JOB_RUN_STATUS_UNKNOWN:"CMDBRE_JOB_RUN_STATUS_UNKNOWN"
    }
    cmdb_const['CMDBRE_JOB_STATUS'] = {
    CMDBRE_JOB_STATUJOB_UNKNOWN:"CMDBRE_JOB_STATUJOB_UNKNOWN",
    CMDBRE_JOB_STATUS_ACTIVE:"CMDBRE_JOB_STATUS_ACTIVE",
    CMDBRE_JOB_STATUS_INACTIVE:"CMDBRE_JOB_STATUS_INACTIVE",
    CMDBRE_JOB_STATUS_NOT_EXISTS:"CMDBRE_JOB_STATUS_NOT_EXISTS"
    }
    cmdb_const['CMDBRE_JOB_STATUS'] = {
    CMDB_ATTR_AUDITTYPE_AUDIT:"CMDB_ATTR_AUDITTYPE_AUDIT",
    CMDB_ATTR_AUDITTYPE_COPY:"CMDB_ATTR_AUDITTYPE_COPY",
    CMDB_ATTR_AUDITTYPE_NONE:"CMDB_ATTR_AUDITTYPE_NONE"
    }
    cmdb_const['rest'].update({
    CMDB_ATTR_ID_FEDERATED_KEYLINK_PRODUCT_KEY:"CMDB_ATTR_ID_FEDERATED_KEYLINK_PRODUCT_KEY",
    CMDB_GET_DATASET_MODE_CURRENT:"CMDB_GET_DATASET_MODE_CURRENT",
    CMDB_GET_MASK_NONE:"CMDB_GET_MASK_NONE",
    CMDB_DEPLOYABLE_APP_NAME:"CMDB_DEPLOYABLE_APP_NAME"
    })